<?php
// Auto-generated by Certxa Blog Manager — do not edit manually.
// Slug: missed-calls-nail-salon-ai-receptionist
// Serving /blog/missed-calls-nail-salon-ai-receptionist as a real filesystem path for optimal SEO indexing.
$_GET['blog_slug'] = 'missed-calls-nail-salon-ai-receptionist';
require dirname(__DIR__) . '/article.php';
