<?php
// Auto-generated by Certxa Blog Manager — do not edit manually.
// Slug: nail-salon-client-records-notes
// Serving /blog/nail-salon-client-records-notes as a real filesystem path for optimal SEO indexing.
$_GET['blog_slug'] = 'nail-salon-client-records-notes';
require dirname(__DIR__) . '/article.php';
