/**
 * setup-cron.ts
 *
 * Sets up a cron job to periodically generate website data files.
 * This ensures that published websites always have fresh data available
 * for the self-building website feature.
 *
 * Usage:
 *   pnpm --filter @workspace/scripts run setup-cron
 *   pnpm --filter @workspace/scripts run setup-cron -- --interval 5
 *
 * Options:
 *   --interval <min>   Interval in minutes between runs (default: 5)
 *   --out <dir>        Output directory for generated files (default: ./website-data)
 *   --remove           Remove the cron job instead of installing it
 *   --dry-run          Show what would be installed without making changes
 */

import { execSync } from "child_process";
import path from "path";

// ── CLI argument parsing ──────────────────────────────────────────────────────

const args = process.argv.slice(2);

function getArg(flag: string): string | undefined {
  const i = args.indexOf(flag);
  return i !== -1 && i + 1 < args.length ? args[i + 1] : undefined;
}

function hasFlag(flag: string): boolean {
  return args.includes(flag);
}

const INTERVAL_MINUTES = parseInt(getArg("--interval") ?? "5", 10);
const OUT_DIR = getArg("--out") ?? path.resolve(process.cwd(), "website-data");
const REMOVE = hasFlag("--remove");
const DRY_RUN = hasFlag("--dry-run");

// ── Cron job configuration ────────────────────────────────────────────────────

const CRON_NAME = "certxa-website-data";
const PROJECT_ROOT = path.resolve(__dirname, "..", "..", "..");
const SCRIPT_PATH = path.join(PROJECT_ROOT, "scripts", "src", "generate-website-data.ts");
const LOG_DIR = path.join(PROJECT_ROOT, "logs");

function getCronExpression(minutes: number): string {
  // Simple cron expression: run every N minutes
  return `*/${minutes} * * * *`;
}

function getCronJob(minutes: number): string {
  const cronExpr = getCronExpression(minutes);
  const logFile = path.join(LOG_DIR, `${CRON_NAME}.log`);

  return `# CertXA Website Data Generator
# Generated by setup-cron.ts
# Regenerates JSON data files for all published websites

${cronExpr} cd ${PROJECT_ROOT} && pnpm --filter @workspace/scripts run generate-website-data -- --out ${OUT_DIR} >> ${logFile} 2>&1
`;
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main(): void {
  console.log("CertXA Cron Job Setup");
  console.log(`  Interval : ${INTERVAL_MINUTES} minute(s)`);
  console.log(`  Output   : ${OUT_DIR}`);
  console.log(`  Action   : ${REMOVE ? "Remove" : "Install"}`);
  console.log(`  Dry run  : ${DRY_RUN ? "yes" : "no"}`);
  console.log("");

  if (REMOVE) {
    // Remove cron job
    const cmd = DRY_RUN
      ? `echo "[dry-run] Would remove crontab entry for ${CRON_NAME}"`
      : `(crontab -l 2>/dev/null | grep -v "${CRON_NAME}") | crontab -`;

    console.log(`Command: ${cmd}`);
    if (!DRY_RUN) {
      try {
        execSync(cmd, { stdio: "inherit" });
        console.log(`\n✓ Cron job "${CRON_NAME}" removed successfully`);
      } catch (err) {
        console.error("Failed to remove cron job:", err);
        process.exit(1);
      }
    }
  } else {
    // Install cron job
    const cronJob = getCronJob(INTERVAL_MINUTES);

    if (DRY_RUN) {
      console.log("[dry-run] Would install the following crontab entry:\n");
      console.log(cronJob);
    } else {
      // Ensure log directory exists
      try {
        execSync(`mkdir -p ${LOG_DIR}`, { stdio: "ignore" });
      } catch {
        // Ignore errors - directory might already exist
      }

      // Install cron job
      const cmd = `(crontab -l 2>/dev/null | grep -v "${CRON_NAME}"; echo "${cronJob.replace(/"/g, '\\"')}") | crontab -`;
      console.log(`Installing cron job...`);

      try {
        execSync(cmd, { stdio: "inherit" });
        console.log(`\n✓ Cron job "${CRON_NAME}" installed successfully`);
        console.log(`  The website data will be regenerated every ${INTERVAL_MINUTES} minute(s)`);
        console.log(`  Logs will be written to: ${path.join(LOG_DIR, `${CRON_NAME}.log`)}`);
        console.log(`\nTo verify: crontab -l | grep ${CRON_NAME}`);
        console.log(`To remove: pnpm --filter @workspace/scripts run setup-cron -- --remove`);
      } catch (err) {
        console.error("Failed to install cron job:", err);
        process.exit(1);
      }
    }
  }
}

main();
