<?php
// Auto-generated by Certxa Blog Manager — do not edit manually.
// Slug: nail-salon-payment-system-pos
// Serving /blog/nail-salon-payment-system-pos as a real filesystem path for optimal SEO indexing.
$_GET['blog_slug'] = 'nail-salon-payment-system-pos';
require dirname(__DIR__) . '/article.php';
