import { db } from "../db";
import { storeSettings, payoutRuns } from "@shared/schema";
import { eq, and, lte, isNotNull } from "drizzle-orm";
import { sql } from "drizzle-orm";

type Frequency = "weekly" | "biweekly" | "semimonthly" | "monthly";

interface PayrollSchedule {
  enabled: boolean;
  frequency: Frequency;
  anchorDate: string | null;
  autoApproveDelayHours: number;
}

// ─── Period Calculator ────────────────────────────────────────────────────────

/**
 * Returns the most recently CLOSED pay period (end date < today).
 * Returns null if no complete period exists yet.
 */
export function getLastClosedPeriod(
  frequency: Frequency,
  anchorDate: string | null,
  now: Date = new Date()
): { periodStart: string; periodEnd: string } | null {
  const today = new Date(now);
  today.setHours(0, 0, 0, 0);
  const fmt = (d: Date) => d.toISOString().slice(0, 10);

  if (frequency === "monthly") {
    const y = today.getFullYear();
    const m = today.getMonth(); // 0-based
    const prevM = m === 0 ? 11 : m - 1;
    const prevY = m === 0 ? y - 1 : y;
    return {
      periodStart: fmt(new Date(prevY, prevM, 1)),
      periodEnd:   fmt(new Date(y, m, 0)), // last day of prev month
    };
  }

  if (frequency === "semimonthly") {
    const y = today.getFullYear();
    const m = today.getMonth();
    const d = today.getDate();
    if (d >= 16) {
      // 1st–15th of this month just closed
      return {
        periodStart: fmt(new Date(y, m, 1)),
        periodEnd:   fmt(new Date(y, m, 15)),
      };
    } else {
      // 16th–EOM of prev month just closed
      const prevM = m === 0 ? 11 : m - 1;
      const prevY = m === 0 ? y - 1 : y;
      return {
        periodStart: fmt(new Date(prevY, prevM, 16)),
        periodEnd:   fmt(new Date(prevY, prevM + 1, 0)), // last day of prevM
      };
    }
  }

  if (frequency === "weekly" || frequency === "biweekly") {
    if (!anchorDate) return null;
    const anchor = new Date(anchorDate + "T00:00:00");
    anchor.setHours(0, 0, 0, 0);
    const periodLen = frequency === "weekly" ? 7 : 14;
    const diffDays = Math.floor((today.getTime() - anchor.getTime()) / 86_400_000);
    if (diffDays < periodLen) return null; // no complete period yet
    const periodsElapsed = Math.floor(diffDays / periodLen);
    const startOffset    = (periodsElapsed - 1) * periodLen;
    const endOffset      = periodsElapsed * periodLen - 1;
    return {
      periodStart: fmt(new Date(anchor.getTime() + startOffset * 86_400_000)),
      periodEnd:   fmt(new Date(anchor.getTime() + endOffset   * 86_400_000)),
    };
  }

  return null;
}

// ─── Schema migrations (idempotent) ──────────────────────────────────────────

async function applyMigrations(): Promise<void> {
  try {
    await db.execute(
      sql`ALTER TABLE payout_runs ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN NOT NULL DEFAULT false`
    );
    await db.execute(
      sql`ALTER TABLE payout_runs ADD COLUMN IF NOT EXISTS auto_approve_after TIMESTAMPTZ`
    );
  } catch (err) {
    console.warn("[PayrollScheduler] Migration warning (columns may already exist):", err);
  }
}

// ─── Scheduler tick ───────────────────────────────────────────────────────────

async function runPayrollTick(): Promise<void> {
  // Lazy import to avoid circular-dependency issues at module load time
  const { createPayoutRunForPeriod, approvePayoutRunById } = await import("../routes/contractorPayouts.js");

  // ── Pass 1: auto-generate draft runs for newly closed periods ─────────────
  const allSettings = await db.select().from(storeSettings);

  for (const row of allSettings) {
    try {
      const prefs: Record<string, any> = row.preferences
        ? JSON.parse(String(row.preferences))
        : {};
      const schedule = prefs.payrollSchedule as PayrollSchedule | undefined;
      if (!schedule?.enabled) continue;

      const period = getLastClosedPeriod(
        schedule.frequency,
        schedule.anchorDate ?? null
      );
      if (!period) continue;

      // Idempotency: skip if a non-cancelled run already exists for this period
      const existing = await db
        .select({ id: payoutRuns.id })
        .from(payoutRuns)
        .where(and(
          eq(payoutRuns.storeId,      row.storeId),
          eq(payoutRuns.periodStart,  period.periodStart),
          eq(payoutRuns.periodEnd,    period.periodEnd),
        ));

      if (existing.length > 0) continue;

      const delayHours      = Number(schedule.autoApproveDelayHours ?? 48);
      const autoApproveAfter = new Date(Date.now() + delayHours * 3_600_000);

      const result = await createPayoutRunForPeriod(
        row.storeId,
        period.periodStart,
        period.periodEnd,
        {
          notes:            `Auto-generated (${schedule.frequency} schedule)`,
          autoGenerated:    true,
          autoApproveAfter,
        }
      );

      if (result) {
        console.log(
          `[PayrollScheduler] Created draft run #${result.run.id} for store ${row.storeId}: ` +
          `${period.periodStart} → ${period.periodEnd} ` +
          `(auto-approve ${autoApproveAfter.toISOString()})`
        );
      }
    } catch (storeErr) {
      console.error(`[PayrollScheduler] Error for store ${row.storeId}:`, storeErr);
    }
  }

  // ── Pass 2: auto-approve runs whose review window has elapsed ─────────────
  const now = new Date();
  const pendingApproval = await db
    .select()
    .from(payoutRuns)
    .where(and(
      eq(payoutRuns.status,        "draft"),
      eq(payoutRuns.autoGenerated, true),
      isNotNull(payoutRuns.autoApproveAfter),
      lte(payoutRuns.autoApproveAfter, now),
    ));

  for (const run of pendingApproval) {
    try {
      const result = await approvePayoutRunById(run.id, null);
      console.log(
        `[PayrollScheduler] Auto-approved run #${run.id} for store ${run.storeId}: status=${result.status}`
      );
    } catch (approveErr) {
      console.error(`[PayrollScheduler] Auto-approve failed for run #${run.id}:`, approveErr);
    }
  }
}

// ─── Entry point ─────────────────────────────────────────────────────────────

export function startPayrollScheduler(): void {
  applyMigrations()
    .then(() => {
      const tick = () =>
        runPayrollTick().catch(e => console.error("[PayrollScheduler] Tick error:", e));
      tick(); // run immediately on boot
      setInterval(tick, 60 * 60 * 1000); // then every hour
      console.log("[PayrollScheduler] Started — checks every hour for closed pay periods");
    })
    .catch(err => {
      console.error("[PayrollScheduler] Migration failed, scheduler not started:", err);
    });
}
