<?php
// Auto-generated by Certxa Blog Manager — do not edit manually.
// Article: How to price your menu in 2026
// Slug: how-to-price-your-menu-in-2026
// Serving /blog/how-to-price-your-menu-in-2026 as a real filesystem path for optimal SEO indexing.
$_GET['blog_slug'] = 'how-to-price-your-menu-in-2026';
require dirname(__DIR__) . '/article.php';
