/**
 * sslProvisioner.ts
 *
 * Provisions and revokes Let's Encrypt SSL certificates for custom domains
 * used by the Website Builder. Runs on the VPS alongside nginx.
 *
 * Flow (domain activation):
 *   1. Write HTTP-only nginx vhost  (serves ACME challenge + proxies to API)
 *   2. nginx -s reload
 *   3. certbot certonly --webroot -d <domain>
 *   4. Replace vhost with full SSL version
 *   5. nginx -s reload
 *
 * Flow (domain removal):
 *   1. certbot delete --cert-name <domain>
 *   2. Remove /etc/nginx/conf.d/certxa-custom-<domain>.conf
 *   3. nginx -s reload
 *
 * Graceful degradation: if certbot/nginx are not installed (dev / Replit
 * environment) every step logs a warning and returns a "skipped" result
 * instead of throwing, so domain activation still completes.
 */

import { exec } from "child_process";
import { promisify } from "util";
import fs from "fs";
import path from "path";

const execAsync = promisify(exec);

const NGINX_CONF_DIR = process.env.NGINX_CONF_DIR ?? "/etc/nginx/conf.d";
const ACME_WEBROOT   = process.env.ACME_WEBROOT   ?? "/var/www/letsencrypt";
const CERTBOT_EMAIL  = process.env.CERTBOT_EMAIL   ?? "admin@certxa.com";

/** Port the API server listens on — nginx proxies custom-domain traffic here */
const API_PORT = process.env.PORT ?? process.env.API_PORT ?? "9200";

// ── helpers ───────────────────────────────────────────────────────────────────

function vhostPath(domain: string): string {
  return path.join(NGINX_CONF_DIR, `certxa-custom-${domain}.conf`);
}

/** Safely sanitise a domain so it can't escape shell arguments */
function assertSafeDomain(domain: string): void {
  if (!/^[a-zA-Z0-9._-]+$/.test(domain)) {
    throw new Error(`Unsafe domain name rejected: ${domain}`);
  }
}

async function isBinaryAvailable(bin: string): Promise<boolean> {
  try {
    await execAsync(`which ${bin}`);
    return true;
  } catch {
    return false;
  }
}

async function reloadNginx(): Promise<void> {
  await execAsync("nginx -s reload");
}

// ── nginx vhost templates ─────────────────────────────────────────────────────

/**
 * Temporary HTTP-only block written before certbot runs.
 * Serves the ACME webroot challenge and proxies everything else to the API
 * so the Coming-Soon / verification page still renders during provisioning.
 *
 * NOTE: We only listen for the apex domain here. `www` is handled by the
 * separate www-redirect block (or ignored if the user hasn't set up a www record).
 * Certbot only needs to serve the ACME challenge for the domains it verifies,
 * and we only request the apex in certbot — see `buildCertbotCmd`.
 */
function httpOnlyVhost(domain: string): string {
  return `# certxa — custom domain (HTTP only, SSL provisioning in progress)
# Generated by sslProvisioner.ts — do not edit manually.
server {
    listen 80;
    listen [::]:80;
    server_name ${domain};

    # ACME webroot challenge
    location /.well-known/acme-challenge/ {
        root ${ACME_WEBROOT};
    }

    # Proxy everything else to the Certxa API (handles tenant routing)
    location / {
        proxy_pass         http://127.0.0.1:${API_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection        "";
    }
}

# Optional www redirect (HTTP only) — works whether or not www DNS is set up
server {
    listen 80;
    listen [::]:80;
    server_name www.${domain};

    location /.well-known/acme-challenge/ {
        root ${ACME_WEBROOT};
    }

    location / {
        return 301 http://${domain}$request_uri;
    }
}
`;
}

/**
 * Full SSL vhost written after certbot succeeds.
 *
 * Architecture:
 *  - The apex domain (domain.com) gets a Let's Encrypt cert and full HTTPS.
 *  - www.domain.com on HTTP redirects to https://domain.com (no www cert needed).
 *  - If the user later sets up www DNS, their browser will follow the redirect.
 *
 * Certbot only requests a cert for the apex domain. This avoids failures
 * when the user's DNS only has an A record for the apex, not www.
 */
function sslVhost(domain: string): string {
  return `# certxa — custom domain (HTTPS)
# Generated by sslProvisioner.ts — do not edit manually.

# HTTP apex → HTTPS redirect (also serves ACME for renewals)
server {
    listen 80;
    listen [::]:80;
    server_name ${domain};

    # ACME webroot challenge (needed for certbot renewals)
    location /.well-known/acme-challenge/ {
        root ${ACME_WEBROOT};
    }

    location / {
        return 301 https://${domain}$request_uri;
    }
}

# www HTTP → apex HTTPS redirect (no cert required for www)
server {
    listen 80;
    listen [::]:80;
    server_name www.${domain};

    location /.well-known/acme-challenge/ {
        root ${ACME_WEBROOT};
    }

    location / {
        return 301 https://${domain}$request_uri;
    }
}

# HTTPS apex — proxy to Certxa API
# Certificate covers only ${domain} (apex). A cert for www is not required
# because www traffic redirects to https://${domain} on port 80 above.
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${domain};

    # SSL — managed by Certbot (apex-only cert), do not edit these lines manually
    ssl_certificate     /etc/letsencrypt/live/${domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    # Security headers
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Frame-Options           "SAMEORIGIN"                                   always;
    add_header X-Content-Type-Options    "nosniff"                                      always;
    add_header X-XSS-Protection          "1; mode=block"                                always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin"              always;

    client_max_body_size 25m;

    # Proxy everything to the Certxa API (tenant routing handled by subdomain middleware)
    location / {
        proxy_pass         http://127.0.0.1:${API_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header Connection        "";
        proxy_read_timeout  60s;
        proxy_send_timeout  30s;
        proxy_connect_timeout 10s;
    }
}
`;
}

/**
 * Normalize legacy nginx HTTP/2 syntax for broad version compatibility.
 *
 * Some older generated files used:
 *   listen 443 ssl;
 *   listen [::]:443 ssl;
 *   http2 on;
 *
 * On servers without support for the standalone `http2` directive this fails with:
 *   unknown directive "http2"
 *
 * We canonicalize to the widely supported style:
 *   listen 443 ssl http2;
 *   listen [::]:443 ssl http2;
 */
function normalizeHttp2Syntax(vhost: string): string {
  return vhost.replace(
    /listen\s+443\s+ssl;\s*\n\s*listen\s+\[::\]:443\s+ssl;\s*\n\s*http2\s+on;/g,
    "listen 443 ssl http2;\n    listen [::]:443 ssl http2;"
  );
}

// ── public API ────────────────────────────────────────────────────────────────

export type SslProvisionResult =
  | { status: "ok";      certPath: string }
  | { status: "skipped"; reason: string }
  | { status: "error";   message: string };

/**
 * Provision a Let's Encrypt certificate for `domain` and configure nginx.
 * Safe to call in any environment — returns "skipped" when tools are absent.
 */
export async function provisionSsl(domain: string): Promise<SslProvisionResult> {
  try {
    assertSafeDomain(domain);
  } catch (err) {
    return { status: "error", message: (err as Error).message };
  }

  const [hasCertbot, hasNginx] = await Promise.all([
    isBinaryAvailable("certbot"),
    isBinaryAvailable("nginx"),
  ]);

  if (!hasCertbot || !hasNginx) {
    return {
      status: "skipped",
      reason: `certbot=${hasCertbot} nginx=${hasNginx} — skipping SSL provisioning in this environment`,
    };
  }

  // Ensure ACME webroot directory exists
  fs.mkdirSync(ACME_WEBROOT, { recursive: true });

  // 1. Write HTTP-only vhost so ACME challenge can be served
  fs.writeFileSync(vhostPath(domain), normalizeHttp2Syntax(httpOnlyVhost(domain)), "utf8");

  // 2. Reload nginx to pick up the new vhost
  try {
    await reloadNginx();
  } catch (err) {
    // Non-fatal — cert may still be obtainable; log and continue
    console.warn(`[SSL] nginx reload before certbot failed: ${(err as Error).message}`);
  }

  // 3. Run certbot — apex domain only.
  //
  // We deliberately do NOT include www.${domain} here.
  // Reason: many users only set an A record for the apex domain; if www DNS
  // isn't pointed to this server, certbot's ACME challenge for www.${domain}
  // fails and NO certificate is issued at all. Without a cert, Nginx falls
  // back to the default certxa.com certificate for HTTPS requests, causing
  // the "wrong certificate" privacy error users see in their browser.
  //
  // www traffic is handled by a plain HTTP 301 redirect to https://${domain}
  // in the SSL vhost template — no www cert is required for that.
  const certbotCmd = [
    "certbot certonly",
    "--webroot",
    `--webroot-path=${ACME_WEBROOT}`,
    `--email=${CERTBOT_EMAIL}`,
    "--agree-tos",
    "--non-interactive",
    `--cert-name=${domain}`,
    `-d ${domain}`,
  ].join(" ");

  try {
    const { stderr } = await execAsync(certbotCmd);
    if (stderr) console.warn(`[SSL] certbot stderr: ${stderr}`);
  } catch (err) {
    const message = (err as Error).message;
    console.error(`[SSL] certbot failed for ${domain}: ${message}`);
    // Leave the HTTP-only vhost in place so the site still serves over HTTP
    return { status: "error", message: `certbot: ${message}` };
  }

  // 4. Replace vhost with full SSL version
  const certPath = `/etc/letsencrypt/live/${domain}/fullchain.pem`;
  fs.writeFileSync(vhostPath(domain), normalizeHttp2Syntax(sslVhost(domain)), "utf8");

  // 5. Reload nginx with the SSL vhost
  try {
    await reloadNginx();
  } catch (err) {
    return { status: "error", message: `nginx reload after cert: ${(err as Error).message}` };
  }

  console.info(`[SSL] Certificate provisioned and nginx reloaded for ${domain}`);
  return { status: "ok", certPath };
}

/**
 * Revoke and delete a Let's Encrypt certificate, and remove the nginx vhost.
 * Safe to call when the tools are absent — logs and skips gracefully.
 */
export async function revokeSSL(domain: string): Promise<void> {
  try {
    assertSafeDomain(domain);
  } catch {
    return;
  }

  const [hasCertbot, hasNginx] = await Promise.all([
    isBinaryAvailable("certbot"),
    isBinaryAvailable("nginx"),
  ]);

  // Remove nginx vhost regardless of certbot availability
  const confFile = vhostPath(domain);
  if (fs.existsSync(confFile)) {
    fs.unlinkSync(confFile);
    console.info(`[SSL] Removed nginx vhost for ${domain}`);
  }

  if (hasCertbot) {
    try {
      await execAsync(`certbot delete --cert-name ${domain} --non-interactive`);
      console.info(`[SSL] Certbot cert deleted for ${domain}`);
    } catch (err) {
      console.warn(`[SSL] certbot delete failed for ${domain}: ${(err as Error).message}`);
    }
  }

  if (hasNginx) {
    try {
      await reloadNginx();
    } catch (err) {
      console.warn(`[SSL] nginx reload after revocation failed: ${(err as Error).message}`);
    }
  }
}
