import OpenAI from "openai";
import { pool } from "../db.js";

export type LangCode = "es" | "vi" | "zh" | "ko";
export type EntityType = "category" | "service" | "addon" | "product";

const LANG_NAMES: Record<LangCode, string> = {
  es: "Spanish",
  vi: "Vietnamese",
  zh: "Chinese (Simplified)",
  ko: "Korean",
};

const TARGET_LANGS: LangCode[] = ["es", "vi", "zh", "ko"];

function getOpenAI(): OpenAI | null {
  const key = process.env.AI_INTEGRATIONS_OPENAI_API_KEY || process.env.OPENAI_API_KEY;
  if (!key) return null;
  return new OpenAI({ apiKey: key });
}

interface TranslateInput {
  entityType: EntityType;
  entityId: number;
  name: string;
  description?: string | null;
}

async function translateOne(
  openai: OpenAI,
  input: TranslateInput,
  lang: LangCode
): Promise<void> {
  const langName = LANG_NAMES[lang];
  const hasDesc = !!input.description?.trim();

  const userContent = hasDesc
    ? `Translate these salon/beauty service business terms from English to ${langName}.\n\nName: ${input.name}\nDescription: ${input.description}\n\nRespond with ONLY a JSON object: {"name":"...","description":"..."}`
    : `Translate this salon/beauty service business term from English to ${langName}.\n\nName: ${input.name}\n\nRespond with ONLY a JSON object: {"name":"..."}`;

  const completion = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      {
        role: "system",
        content:
          "You are a professional translator specializing in beauty salon and nail salon terminology. Translate accurately and naturally. Preserve brand names, chemical terms, and technical service names without translating them if they are better left as-is in the target language. Return only the requested JSON, no markdown.",
      },
      { role: "user", content: userContent },
    ],
    temperature: 0.3,
    max_tokens: 300,
  });

  const raw = completion.choices[0]?.message?.content?.trim() ?? "{}";
  let parsed: { name?: string; description?: string };
  try {
    parsed = JSON.parse(raw);
  } catch {
    const nameMatch = raw.match(/"name"\s*:\s*"([^"]+)"/);
    parsed = { name: nameMatch?.[1] ?? input.name };
  }

  const translatedName = parsed.name?.trim() || input.name;
  const translatedDesc = hasDesc ? (parsed.description?.trim() ?? null) : null;

  await pool.query(
    `INSERT INTO entity_translations
       (entity_type, entity_id, language, name, description, auto_generated, is_edited_by_user, confidence_score, updated_at)
     VALUES ($1, $2, $3, $4, $5, TRUE, FALSE, 0.9, NOW())
     ON CONFLICT (entity_type, entity_id, language) DO UPDATE
       SET name             = EXCLUDED.name,
           description      = EXCLUDED.description,
           auto_generated   = CASE WHEN entity_translations.is_edited_by_user THEN entity_translations.auto_generated ELSE TRUE END,
           confidence_score = CASE WHEN entity_translations.is_edited_by_user THEN entity_translations.confidence_score ELSE 0.9 END,
           updated_at       = CASE WHEN entity_translations.is_edited_by_user THEN entity_translations.updated_at ELSE NOW() END`,
    [input.entityType, input.entityId, lang, translatedName, translatedDesc]
  );
}

export function triggerTranslation(input: TranslateInput): void {
  const openai = getOpenAI();
  if (!openai) {
    console.warn("[Translations] No OpenAI key — skipping auto-translation for", input.entityType, input.entityId);
    return;
  }

  setImmediate(async () => {
    for (const lang of TARGET_LANGS) {
      try {
        await translateOne(openai, input, lang);
      } catch (err) {
        console.error(`[Translations] Failed ${input.entityType}#${input.entityId} → ${lang}:`, err);
      }
    }
    console.log(`[Translations] ✓ ${input.entityType}#${input.entityId} translated into ${TARGET_LANGS.join(", ")}`);
  });
}

export async function getTranslations(
  entityType: EntityType,
  entityId: number
): Promise<Array<{ language: string; name: string; description: string | null; autoGenerated: boolean; isEditedByUser: boolean; confidenceScore: number | null; updatedAt: string }>> {
  const { rows } = await pool.query(
    `SELECT language, name, description, auto_generated, is_edited_by_user, confidence_score, updated_at
     FROM entity_translations
     WHERE entity_type = $1 AND entity_id = $2
     ORDER BY language`,
    [entityType, entityId]
  );
  return rows.map((r: any) => ({
    language: r.language,
    name: r.name,
    description: r.description,
    autoGenerated: r.auto_generated,
    isEditedByUser: r.is_edited_by_user,
    confidenceScore: r.confidence_score,
    updatedAt: r.updated_at,
  }));
}

export async function upsertTranslation(
  entityType: EntityType,
  entityId: number,
  language: LangCode,
  name: string,
  description?: string | null
): Promise<void> {
  await pool.query(
    `INSERT INTO entity_translations
       (entity_type, entity_id, language, name, description, auto_generated, is_edited_by_user, updated_at)
     VALUES ($1, $2, $3, $4, $5, FALSE, TRUE, NOW())
     ON CONFLICT (entity_type, entity_id, language) DO UPDATE
       SET name              = EXCLUDED.name,
           description       = EXCLUDED.description,
           is_edited_by_user = TRUE,
           auto_generated    = FALSE,
           updated_at        = NOW()`,
    [entityType, entityId, language, name.trim(), description?.trim() ?? null]
  );
}

export async function deleteTranslationsForEntity(
  entityType: EntityType,
  entityId: number
): Promise<void> {
  await pool.query(
    `DELETE FROM entity_translations WHERE entity_type = $1 AND entity_id = $2`,
    [entityType, entityId]
  );
}

export async function getStoreTranslations(storeId: number): Promise<{
  categories: any[];
  services: any[];
  addons: any[];
  products: any[];
}> {
  const { rows: catRows } = await pool.query(`
    SELECT sc.id, sc.name AS base_name,
           t.language, t.name AS translated_name, t.description,
           t.auto_generated, t.is_edited_by_user, t.updated_at
    FROM service_categories sc
    LEFT JOIN entity_translations t ON t.entity_type = 'category' AND t.entity_id = sc.id
    WHERE sc.store_id = $1
    ORDER BY sc.name, t.language`, [storeId]);

  const { rows: svcRows } = await pool.query(`
    SELECT s.id, s.name AS base_name, s.description AS base_description,
           t.language, t.name AS translated_name, t.description,
           t.auto_generated, t.is_edited_by_user, t.updated_at
    FROM services s
    LEFT JOIN entity_translations t ON t.entity_type = 'service' AND t.entity_id = s.id
    WHERE s.store_id = $1
    ORDER BY s.name, t.language`, [storeId]);

  const { rows: addonRows } = await pool.query(`
    SELECT a.id, a.name AS base_name, a.description AS base_description,
           t.language, t.name AS translated_name, t.description,
           t.auto_generated, t.is_edited_by_user, t.updated_at
    FROM addons a
    LEFT JOIN entity_translations t ON t.entity_type = 'addon' AND t.entity_id = a.id
    WHERE a.store_id = $1
    ORDER BY a.name, t.language`, [storeId]);

  const { rows: prodRows } = await pool.query(`
    SELECT p.id, p.name AS base_name,
           t.language, t.name AS translated_name, t.description,
           t.auto_generated, t.is_edited_by_user, t.updated_at
    FROM products p
    LEFT JOIN entity_translations t ON t.entity_type = 'product' AND t.entity_id = p.id
    WHERE p.store_id = $1
    ORDER BY p.name, t.language`, [storeId]);

  return {
    categories: catRows,
    services: svcRows,
    addons: addonRows,
    products: prodRows,
  };
}

export async function ensureTranslationsTable(): Promise<void> {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS entity_translations (
      id                SERIAL PRIMARY KEY,
      entity_type       TEXT NOT NULL,
      entity_id         INTEGER NOT NULL,
      language          TEXT NOT NULL,
      name              TEXT NOT NULL,
      description       TEXT,
      auto_generated    BOOLEAN NOT NULL DEFAULT TRUE,
      is_edited_by_user BOOLEAN NOT NULL DEFAULT FALSE,
      confidence_score  REAL,
      created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE (entity_type, entity_id, language)
    );
    CREATE INDEX IF NOT EXISTS idx_entity_translations_lookup
      ON entity_translations (entity_type, entity_id);
  `);
}
