/**
 * Blog routes
 *
 * Public:
 *   GET  /api/blog/posts          – list published posts
 *   GET  /api/blog/posts/:slug    – single published post by slug
 *
 * Admin (isAdmin required):
 *   GET    /api/admin/blog/posts          – all posts (including drafts)
 *   POST   /api/admin/blog/posts          – create post
 *   PATCH  /api/admin/blog/posts/:id      – update post
 *   DELETE /api/admin/blog/posts/:id      – delete post
 *   POST   /api/admin/blog/posts/:id/publish   – publish
 *   POST   /api/admin/blog/posts/:id/unpublish – unpublish
 *
 * On publish:  writes php/blog/<slug>/default.php so the PHP router serves the
 *              article at a real filesystem path — better for Google crawling.
 * On unpublish/delete: removes the stub directory.
 */

import { Router, Request, Response } from "express";
import fs from "fs/promises";
import path from "path";
import { pool } from "../db.js";

export const blogRouter = Router();

// Absolute path to php/blog/ relative to the API server working directory
const PHP_BLOG_DIR = path.resolve(process.cwd(), "../../php/blog");

// ── helpers ──────────────────────────────────────────────────────────────────

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

async function requireAdmin(req: Request, res: Response): Promise<boolean> {
  const session = (req as any).session;
  if (!session?.userId) {
    res.status(401).json({ error: "Not authenticated" });
    return false;
  }
  const result = await pool.query(
    `SELECT is_admin FROM users WHERE id = $1 LIMIT 1`,
    [session.userId]
  );
  if (!result.rows[0]?.is_admin) {
    res.status(403).json({ error: "Admin access required" });
    return false;
  }
  return true;
}

/**
 * Write php/blog/<slug>/default.php — a tiny PHP stub that routes the
 * request through article.php. The PHP router's existing directory→default.php
 * logic serves this file naturally, so /blog/<slug> resolves to a real
 * filesystem path that Googlebot can reliably crawl.
 */
async function writePostStub(slug: string, title: string): Promise<void> {
  try {
    const dir = path.join(PHP_BLOG_DIR, slug);
    await fs.mkdir(dir, { recursive: true });
    const stub = `<?php
// Auto-generated by Certxa Blog Manager — do not edit manually.
// Article: ${title.replace(/\*\//g, "")}
// Slug: ${slug}
// Serving /blog/${slug} as a real filesystem path for optimal SEO indexing.
$_GET['blog_slug'] = '${slug.replace(/'/g, "\\'")}';
require dirname(__DIR__) . '/article.php';
`;
    await fs.writeFile(path.join(dir, "default.php"), stub, "utf8");
    console.log(`[blog] Stub written: php/blog/${slug}/default.php`);
  } catch (err) {
    console.error(`[blog] Failed to write stub for slug "${slug}":`, err);
  }
}

/**
 * Remove php/blog/<slug>/ when a post is deleted or unpublished.
 * Only removes the directory if it contains only our generated default.php.
 */
async function deletePostStub(slug: string): Promise<void> {
  try {
    const dir = path.join(PHP_BLOG_DIR, slug);
    await fs.rm(dir, { recursive: true, force: true });
    console.log(`[blog] Stub removed: php/blog/${slug}/`);
  } catch (err) {
    // Non-fatal — directory may not exist
  }
}

// ── Public routes ─────────────────────────────────────────────────────────────

// GET /api/blog/posts
blogRouter.get("/api/blog/posts", async (req: Request, res: Response) => {
  try {
    const { category, limit = "20", offset = "0" } = req.query as Record<string, string>;
    const hasCategory = category && category !== "All";

    let query = `
      SELECT id, title, slug, excerpt, category, author_name,
             cover_color, cover_emoji, read_time, is_featured,
             published_at, created_at
      FROM blog_posts
      WHERE status = 'published'
    `;
    const params: any[] = [];
    if (hasCategory) {
      params.push(category);
      query += ` AND category = $${params.length}`;
    }
    query += ` ORDER BY is_featured DESC, published_at DESC NULLS LAST`;
    params.push(parseInt(limit, 10), parseInt(offset, 10));
    query += ` LIMIT $${params.length - 1} OFFSET $${params.length}`;

    const result = await pool.query(query, params);

    const countParams = hasCategory ? [category] : [];
    const countResult = await pool.query(
      `SELECT COUNT(*) FROM blog_posts WHERE status = 'published'${hasCategory ? ` AND category = $1` : ""}`,
      countParams
    );

    res.json({ posts: result.rows, total: parseInt(countResult.rows[0].count, 10) });
  } catch (err) {
    console.error("[blog] GET /api/blog/posts error:", err);
    res.status(500).json({ error: "Failed to fetch posts" });
  }
});

// GET /api/blog/posts/:slug
blogRouter.get("/api/blog/posts/:slug", async (req: Request, res: Response) => {
  try {
    const result = await pool.query(
      `SELECT * FROM blog_posts WHERE slug = $1 AND status = 'published' LIMIT 1`,
      [req.params.slug]
    );
    if (!result.rows[0]) return res.status(404).json({ error: "Post not found" });
    res.json(result.rows[0]);
  } catch (err) {
    console.error("[blog] GET /api/blog/posts/:slug error:", err);
    res.status(500).json({ error: "Failed to fetch post" });
  }
});

// ── Admin routes ──────────────────────────────────────────────────────────────

// GET /api/admin/blog/posts
blogRouter.get("/api/admin/blog/posts", async (req: Request, res: Response) => {
  if (!(await requireAdmin(req, res))) return;
  try {
    const result = await pool.query(
      `SELECT id, title, slug, excerpt, category, author_name,
              cover_color, cover_emoji, read_time, is_featured,
              status, published_at, created_at, updated_at
       FROM blog_posts
       ORDER BY created_at DESC`
    );
    res.json(result.rows);
  } catch (err) {
    console.error("[blog] GET /api/admin/blog/posts error:", err);
    res.status(500).json({ error: "Failed to fetch posts" });
  }
});

// POST /api/admin/blog/posts
blogRouter.post("/api/admin/blog/posts", async (req: Request, res: Response) => {
  if (!(await requireAdmin(req, res))) return;
  try {
    const {
      title, slug, excerpt, content, category = "General",
      author_name = "Certxa Team", cover_color = "#7c3aed",
      cover_emoji = "📝", read_time = "5 min read",
      is_featured = false, status = "draft",
    } = req.body;

    if (!title) return res.status(400).json({ error: "title is required" });
    const finalSlug = slug ? slugify(slug) : slugify(title);

    const result = await pool.query(
      `INSERT INTO blog_posts
         (title, slug, excerpt, content, category, author_name,
          cover_color, cover_emoji, read_time, is_featured, status,
          published_at, created_at, updated_at)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,
               CASE WHEN $11='published' THEN now() ELSE NULL END,
               now(), now())
       RETURNING *`,
      [title, finalSlug, excerpt, content, category, author_name,
       cover_color, cover_emoji, read_time, is_featured, status]
    );
    const post = result.rows[0];

    // Write stub if published
    if (post.status === "published") {
      await writePostStub(post.slug, post.title);
    }

    res.status(201).json(post);
  } catch (err: any) {
    if (err.code === "23505") return res.status(409).json({ error: "Slug already exists" });
    console.error("[blog] POST /api/admin/blog/posts error:", err);
    res.status(500).json({ error: "Failed to create post" });
  }
});

// PATCH /api/admin/blog/posts/:id
blogRouter.patch("/api/admin/blog/posts/:id", async (req: Request, res: Response) => {
  if (!(await requireAdmin(req, res))) return;
  try {
    const id = parseInt(req.params.id as string, 10);

    // Fetch current state so we can handle slug renames and status transitions
    const current = await pool.query(`SELECT slug, status FROM blog_posts WHERE id = $1`, [id]);
    if (!current.rows[0]) return res.status(404).json({ error: "Post not found" });
    const oldSlug = current.rows[0].slug as string;
    const oldStatus = current.rows[0].status as string;

    const {
      title, slug, excerpt, content, category, author_name,
      cover_color, cover_emoji, read_time, is_featured, status,
    } = req.body;

    const finalSlug = slug ? slugify(slug) : undefined;

    const result = await pool.query(
      `UPDATE blog_posts SET
         title        = COALESCE($2, title),
         slug         = COALESCE($3, slug),
         excerpt      = COALESCE($4, excerpt),
         content      = COALESCE($5, content),
         category     = COALESCE($6, category),
         author_name  = COALESCE($7, author_name),
         cover_color  = COALESCE($8, cover_color),
         cover_emoji  = COALESCE($9, cover_emoji),
         read_time    = COALESCE($10, read_time),
         is_featured  = COALESCE($11, is_featured),
         status       = COALESCE($12, status),
         published_at = CASE
           WHEN $12 = 'published' AND published_at IS NULL THEN now()
           WHEN $12 = 'draft' THEN NULL
           ELSE published_at
         END,
         updated_at   = now()
       WHERE id = $1
       RETURNING *`,
      [id, title, finalSlug, excerpt, content, category, author_name,
       cover_color, cover_emoji, read_time, is_featured, status]
    );
    const post = result.rows[0];

    const newSlug = post.slug as string;
    const newStatus = post.status as string;
    const slugChanged = finalSlug && newSlug !== oldSlug;

    if (newStatus === "published") {
      // Remove old stub if slug changed
      if (slugChanged) await deletePostStub(oldSlug);
      await writePostStub(newSlug, post.title);
    } else {
      // Unpublished — remove stub (both old and new slug in case of rename)
      if (slugChanged) await deletePostStub(oldSlug);
      await deletePostStub(newSlug);
    }

    res.json(post);
  } catch (err: any) {
    if (err.code === "23505") return res.status(409).json({ error: "Slug already exists" });
    console.error("[blog] PATCH /api/admin/blog/posts/:id error:", err);
    res.status(500).json({ error: "Failed to update post" });
  }
});

// DELETE /api/admin/blog/posts/:id
blogRouter.delete("/api/admin/blog/posts/:id", async (req: Request, res: Response) => {
  if (!(await requireAdmin(req, res))) return;
  try {
    const result = await pool.query(
      `DELETE FROM blog_posts WHERE id = $1 RETURNING id, slug`,
      [parseInt(req.params.id as string, 10)]
    );
    if (!result.rows[0]) return res.status(404).json({ error: "Post not found" });
    await deletePostStub(result.rows[0].slug);
    res.json({ ok: true });
  } catch (err) {
    console.error("[blog] DELETE /api/admin/blog/posts/:id error:", err);
    res.status(500).json({ error: "Failed to delete post" });
  }
});

// POST /api/admin/blog/posts/:id/publish
blogRouter.post("/api/admin/blog/posts/:id/publish", async (req: Request, res: Response) => {
  if (!(await requireAdmin(req, res))) return;
  try {
    const result = await pool.query(
      `UPDATE blog_posts
       SET status = 'published', published_at = COALESCE(published_at, now()), updated_at = now()
       WHERE id = $1 RETURNING *`,
      [parseInt(req.params.id as string, 10)]
    );
    if (!result.rows[0]) return res.status(404).json({ error: "Post not found" });
    const post = result.rows[0];
    await writePostStub(post.slug, post.title);
    res.json(post);
  } catch (err) {
    console.error("[blog] publish error:", err);
    res.status(500).json({ error: "Failed to publish post" });
  }
});

// POST /api/admin/blog/posts/:id/unpublish
blogRouter.post("/api/admin/blog/posts/:id/unpublish", async (req: Request, res: Response) => {
  if (!(await requireAdmin(req, res))) return;
  try {
    const result = await pool.query(
      `UPDATE blog_posts
       SET status = 'draft', updated_at = now()
       WHERE id = $1 RETURNING *`,
      [parseInt(req.params.id as string, 10)]
    );
    if (!result.rows[0]) return res.status(404).json({ error: "Post not found" });
    await deletePostStub(result.rows[0].slug);
    res.json(result.rows[0]);
  } catch (err) {
    console.error("[blog] unpublish error:", err);
    res.status(500).json({ error: "Failed to unpublish post" });
  }
});
