/**
 * Service Import Routes — AI-powered menu import from photos/PDF + manual review.
 *
 * POST /api/service-import/upload       — upload images/PDF, create job, fire async AI
 * GET  /api/service-import/jobs         — list jobs for current store
 * GET  /api/service-import/jobs/:id     — get job status + ai_result
 * PATCH /api/service-import/jobs/:id/result — owner edits draft (patches ai_result)
 * POST /api/service-import/publish      — create real services from reviewed ai_result
 */

import { Router, Request, Response } from "express";
import multer from "multer";
import { db, pool } from "../db";
import { sql, eq } from "drizzle-orm";
import { services, serviceCategories, locations } from "@shared/schema";
import { resolveSessionStoreId } from "../lib/sessionStore";
import { uploadToR2 } from "../lib/r2";
import {
  sendServiceImportSuccessEmail,
  sendServiceImportFailureEmail,
  getStoreOwnerContact,
} from "../lib/systemEmails";

const router = Router();

// ─── Auth guard ───────────────────────────────────────────────────────────────
async function requireStore(req: Request, res: Response): Promise<number | null> {
  const storeId = await resolveSessionStoreId(req);
  if (!storeId) {
    res.status(401).json({ error: "Not authenticated" });
    return null;
  }
  return storeId;
}

// ─── Multer: images + PDFs, up to 10 files, 20 MB each ──────────────────────
const menuUpload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 20 * 1024 * 1024, files: 10 },
  fileFilter: (_req, file, cb) => {
    const allowed = [
      "image/jpeg",
      "image/png",
      "image/webp",
      "image/heic",
      "image/heif",
      "image/gif",
      "application/pdf",
    ];
    if (allowed.includes(file.mimetype)) {
      cb(null, true);
    } else {
      cb(new Error("Only images (JPEG/PNG/WebP/HEIC) and PDF files are allowed"));
    }
  },
});

// ─── DB helpers ───────────────────────────────────────────────────────────────
async function getJob(jobId: number, storeId: number) {
  const result = await pool.query(
    `SELECT * FROM service_import_jobs WHERE id = $1 AND store_id = $2 LIMIT 1`,
    [jobId, storeId]
  );
  return result.rows[0] ?? null;
}

async function updateJob(
  jobId: number,
  fields: Record<string, unknown>
) {
  const keys = Object.keys(fields);
  const values = Object.values(fields);
  const setClauses = keys.map((k, i) => `${k} = $${i + 2}`).join(", ");
  await pool.query(
    `UPDATE service_import_jobs SET ${setClauses} WHERE id = $1`,
    [jobId, ...values]
  );
}

// ─── Ensure table exists (startup safety) ─────────────────────────────────────
export async function ensureServiceImportTable() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS service_import_jobs (
      id             SERIAL PRIMARY KEY,
      store_id       INTEGER NOT NULL,
      status         TEXT    NOT NULL DEFAULT 'pending',
      import_type    TEXT    NOT NULL DEFAULT 'photos',
      uploaded_files JSONB   NOT NULL DEFAULT '[]',
      ai_result      JSONB,
      error_message  TEXT,
      created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      completed_at   TIMESTAMPTZ,
      notified_at    TIMESTAMPTZ
    )
  `);
  await pool.query(
    `CREATE INDEX IF NOT EXISTS idx_sij_store_id ON service_import_jobs(store_id)`
  );
}

// ─── AI extraction ────────────────────────────────────────────────────────────

interface ExtractedService {
  name: string;
  price: number;
  duration: number;
  description?: string;
}

interface ExtractedCategory {
  name: string;
  services: ExtractedService[];
  confidence?: number;        // 0.0-1.0 (from AI matching)
  isAutoGenerated?: boolean;  // true if category was created by AI
}

interface AIMenuResult {
  categories: ExtractedCategory[];
}

// ─── Fuzzy matching helper for fallback category assignment ───────────────────
function calculateSimilarity(str1: string, str2: string): number {
  const s1 = str1.toLowerCase().trim();
  const s2 = str2.toLowerCase().trim();
  if (s1 === s2) return 1.0;
  
  // Simple Levenshtein distance-based similarity
  const longer = s1.length > s2.length ? s1 : s2;
  const shorter = s1.length > s2.length ? s2 : s1;
  
  if (longer.length === 0) return 1.0;
  
  const editDistance = getEditDistance(longer, shorter);
  return (longer.length - editDistance) / longer.length;
}

function getEditDistance(s1: string, s2: string): number {
  const costs: number[] = [];
  for (let j = 0; j <= s2.length; j++) costs[j] = j;
  
  for (let i = 1; i <= s1.length; i++) {
    let nw = i - 1;
    costs[0] = i;
    for (let j = 1; j <= s2.length; j++) {
      const cj = Math.min(
        1 + Math.min(costs[j], costs[j - 1]),
        nw + (s1[i - 1] === s2[j - 1] ? 0 : 1)
      );
      nw = costs[j];
      costs[j] = cj;
    }
  }
  return costs[s2.length] ?? 0;
}

function getOpenAIConfig(): { apiKey: string; baseURL?: string } {
  const directApiKey = process.env.OPENAI_API_KEY?.trim();
  const integrationApiKey = process.env.AI_INTEGRATIONS_OPENAI_API_KEY?.trim();

  if (directApiKey) return { apiKey: directApiKey };
  if (integrationApiKey) {
    const baseURL = process.env.AI_INTEGRATIONS_OPENAI_BASE_URL?.trim();
    return { apiKey: integrationApiKey, ...(baseURL ? { baseURL } : {}) };
  }

  throw new Error("OpenAI API key is not configured");
}

const SYSTEM_PROMPT = `You are a nail salon service menu parser. The owner has uploaded photos or a PDF of their price board. Extract all services you can identify and return ONLY valid JSON.

Normalize service names to standard nail salon terminology:
- "Gel X" / "Gel-X" / "Gel X Full" / "GelX" → "Gel-X Full Set"
- "Fill Acrylic" / "Acrylic Fill In" / "Fill" (in acrylic context) → "Acrylic Fill"
- "SNS" / "Dipping Powder" / "Dip" → "Dipping Powder"
- "OPI Gel" / "Gel Color" / "Shellac" → "Gel Manicure"
- "Basic" / "Regular" / "Traditional" manicure → "Classic Manicure"
- "Hard Gel" / "Hard Gel Full Set" → "Hard Gel Full Set"
- "Polygel" / "Poly Gel" / "Poly-Gel" → "Polygel Full Set"
- "French" suffix → keep "French" in the name (e.g. "Gel French Manicure")
- Add-ons and variations should be captured as separate services within the closest allowed category.
Use ONLY these seven category names: Manicures, Pedicures, Enhancements, Nail Art, Waxing, Threading, Combos.
Never invent another category. Put acrylic, gel, Gel-X, dip, fills, removals, and extensions under Enhancements. Put designs, charms, French tips, and similar add-ons under Nail Art. Put bundled services under Combos.
For duration, estimate in minutes based on service type if not shown (e.g. manicure=45, pedicure=60, acrylic full set=90).
For prices, extract the numeric value only (no $ sign). If a price range is shown (e.g. "$40-50"), use the lower value.
Return ONLY valid JSON with no markdown, no commentary.

JSON format:
{
  "categories": [
    {
      "name": "Manicures",
      "services": [
        { "name": "Classic Manicure", "price": 25, "duration": 45, "description": "" }
      ]
    }
  ]
}`;

/**
 * Extract services from image files using GPT-4o (vision).
 */
async function extractServicesFromImages(
  imageBuffers: { buffer: Buffer; mimeType: string; originalName: string }[]
): Promise<AIMenuResult> {
  const OpenAI = (await import("openai")).default;
  const openai = new OpenAI(getOpenAIConfig());

  const content: any[] = [
    {
      type: "text",
      text: "Please analyze these nail salon price menu photos and extract all services, categories, prices, and durations. Return structured JSON only.",
    },
  ];

  for (const img of imageBuffers) {
    const base64 = img.buffer.toString("base64");
    const mimeType = img.mimeType.startsWith("image/heic") ? "image/jpeg" : img.mimeType;
    content.push({
      type: "image_url",
      image_url: {
        url: `data:${mimeType};base64,${base64}`,
        detail: "high",
      },
    });
  }

  const completion = await openai.chat.completions.create({
    model: "gpt-4o",
    max_tokens: 4096,
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      { role: "user", content },
    ],
  });

  return parseAIResponse(completion.choices[0]?.message?.content ?? "");
}

/**
 * Extract services from a PDF file using GPT-5.5 with native PDF understanding.
 * The PDF is uploaded to OpenAI's Files API then referenced in the message.
 */
async function extractServicesFromPDF(
  pdfBuffer: Buffer,
  originalName: string
): Promise<AIMenuResult> {
  const { default: OpenAI, toFile } = await import("openai");
  const openai = new OpenAI(getOpenAIConfig());

  // Upload the PDF to OpenAI Files API so the model can read it natively
  const file = await openai.files.create({
    file: await toFile(pdfBuffer, originalName, { type: "application/pdf" }),
    purpose: "user_data",
  });

  console.log(`[ServiceImport] Uploaded PDF to OpenAI Files API: ${file.id}`);

  let completion: any;
  try {
    completion = await openai.chat.completions.create({
      model: "gpt-5.5",
      max_tokens: 4096,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        {
          role: "user",
          content: [
            {
              type: "text",
              text: "Please analyze this nail salon price menu PDF and extract all services, categories, add-ons, variations, and prices. Return structured JSON only.",
            },
            {
              type: "file",
              file: { file_id: file.id },
            } as any,
          ],
        },
      ],
    });
  } finally {
    // Clean up the uploaded file regardless of success/failure
    await openai.files.delete(file.id).catch((e: any) =>
      console.warn(`[ServiceImport] Could not delete OpenAI file ${file.id}:`, e.message)
    );
  }

  return parseAIResponse(completion.choices[0]?.message?.content ?? "");
}

/**
 * Shared JSON response parser — strips markdown fences and validates structure.
 */
function parseAIResponse(raw: string): AIMenuResult {
  const jsonStr = raw
    .replace(/^```json\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/\s*```\s*$/i, "")
    .trim();

  const parsed = JSON.parse(jsonStr) as AIMenuResult;

  if (!Array.isArray(parsed.categories)) {
    throw new Error("AI returned unexpected structure — missing categories array");
  }

  return parsed;
}

// ─── Category Management & Intelligent Matching ────────────────────────────────

/**
 * Fetch all existing service categories for a store.
 */
async function getExistingCategories(storeId: number): Promise<string[]> {
  const result = await db
    .select({ name: serviceCategories.name })
    .from(serviceCategories)
    .where(sql`store_id = ${storeId}`)
    .orderBy(sql`sort_order ASC`);
  return result.map(r => r.name);
}

/**
 * Use AI to match a service to the best existing category.
 * Returns category name + confidence score (0.0-1.0).
 * Returns null if no good match found.
 */
async function matchServiceToCategory(
  serviceName: string,
  description: string | undefined,
  existingCategories: string[]
): Promise<{ categoryName: string; confidence: number } | null> {
  if (existingCategories.length === 0) return null;

  const OpenAI = (await import("openai")).default;
  const openai = new OpenAI(getOpenAIConfig());

  const categoryList = existingCategories.join(", ");
  const prompt = `You are a salon service categorization expert. Given a service, pick the BEST matching category.

Service: "${serviceName}"
${description ? `Description: "${description}"` : ""}

Available categories: ${categoryList}

Respond with ONLY valid JSON (no markdown):
{
  "category": "CATEGORY_NAME",
  "confidence": 0.95
}

Confidence should be:
- 1.0 if perfect match
- 0.8-0.99 if very likely
- 0.6-0.79 if reasonable fit
- 0.0-0.59 if poor fit or uncertain`;

  try {
    const completion = await openai.chat.completions.create({
      model: "gpt-4o",
      max_tokens: 100,
      response_format: { type: "json_object" },
      messages: [{ role: "user", content: prompt }],
    });

    const responseText = completion.choices[0]?.message?.content ?? "{}";
    const parsed = JSON.parse(responseText) as { category: string; confidence: number };
    
    // Validate category is in the list
    const isValid = existingCategories.some(c => c.toLowerCase() === parsed.category.toLowerCase());
    if (!isValid) return null;

    return {
      categoryName: parsed.category,
      confidence: Math.min(1.0, Math.max(0.0, parsed.confidence ?? 0)),
    };
  } catch (err: any) {
    console.warn(`[ServiceImport] AI matching failed for "${serviceName}":`, err.message);
    return null;
  }
}

/**
 * Suggest new category names for unmatched services.
 * Returns array of suggested category names (3-5 suggestions).
 */
async function suggestCategoriesForUnmatched(
  unmatched: ExtractedService[]
): Promise<string[]> {
  if (unmatched.length === 0) return [];

  const OpenAI = (await import("openai")).default;
  const openai = new OpenAI(getOpenAIConfig());

  const serviceList = unmatched.map(s => `- ${s.name}${s.description ? ` (${s.description})` : ""}`).join("\n");
  const prompt = `You are a salon service categorization expert. These services don't fit any existing category. Suggest 3-5 logical category names to group them.

Services:
${serviceList}

Respond with ONLY valid JSON (no markdown):
{
  "suggestedCategories": ["Category 1", "Category 2", "Category 3"]
}

Guidelines:
- Use clear, professional names
- Make names broad enough to hold multiple related services
- Avoid generic names like "Other" or "Misc"
- Names should be 1-3 words`;

  try {
    const completion = await openai.chat.completions.create({
      model: "gpt-4o",
      max_tokens: 200,
      response_format: { type: "json_object" },
      messages: [{ role: "user", content: prompt }],
    });

    const responseText = completion.choices[0]?.message?.content ?? "{}";
    const parsed = JSON.parse(responseText) as { suggestedCategories?: string[] };
    
    return (parsed.suggestedCategories ?? []).filter(c => c && typeof c === "string").slice(0, 5);
  } catch (err: any) {
    console.warn(`[ServiceImport] Category suggestion failed:`, err.message);
    return [];
  }
}

/**
 * Main orchestration: enrich AI result with intelligent category matching & auto-creation.
 *
 * Process:
 * 1. Fetch existing store categories
 * 2. For each service: try AI matching (Tier 1) → fuzzy matching (Tier 2)
 * 3. Collect unmatched services
 * 4. If unmatched exist: suggest new categories & create them in DB
 * 5. Return enriched result with all services assigned + confidence scores
 */
async function enrichAIResultWithCategoryMatching(
  aiResult: AIMenuResult,
  storeId: number
): Promise<AIMenuResult> {
  console.log(`[ServiceImport] Enriching AI result with category matching for store ${storeId}…`);

  // Step 1: Get existing categories
  const existingCategoryNames = await getExistingCategories(storeId);
  console.log(`[ServiceImport] Found ${existingCategoryNames.length} existing categories`);

  // Step 2: Flatten all services and attempt matching
  const allServices: Array<ExtractedService & { originalCategory: string }> = [];
  for (const cat of aiResult.categories) {
    for (const svc of cat.services) {
      allServices.push({
        ...svc,
        originalCategory: cat.name,
      });
    }
  }

  const matchedServices: Map<string, { services: ExtractedService[]; confidence: number; isNew: boolean }> = new Map();
  const unmatchedServices: ExtractedService[] = [];

  for (const svc of allServices) {
    let matched = false;

    // Tier 1: Try AI matching
    if (existingCategoryNames.length > 0) {
      const aiMatch = await matchServiceToCategory(svc.name, svc.description, existingCategoryNames);
      if (aiMatch && aiMatch.confidence >= 0.85) {
        console.log(`[ServiceImport] Service "${svc.name}" matched to "${aiMatch.categoryName}" (confidence: ${aiMatch.confidence})`);
        if (!matchedServices.has(aiMatch.categoryName)) {
          matchedServices.set(aiMatch.categoryName, { services: [], confidence: aiMatch.confidence, isNew: false });
        }
        const entry = matchedServices.get(aiMatch.categoryName)!;
        entry.services.push(svc);
        entry.confidence = (entry.confidence + aiMatch.confidence) / 2;
        matched = true;
      }
    }

    // Tier 2: Fallback to fuzzy matching
    if (!matched && existingCategoryNames.length > 0) {
      let bestMatch: { name: string; similarity: number } | null = null;
      for (const catName of existingCategoryNames) {
        const similarity = calculateSimilarity(svc.name, catName);
        if (similarity >= 0.7 && (!bestMatch || similarity > bestMatch.similarity)) {
          bestMatch = { name: catName, similarity };
        }
      }
      if (bestMatch) {
        console.log(`[ServiceImport] Service "${svc.name}" fuzzy-matched to "${bestMatch.name}" (similarity: ${bestMatch.similarity})`);
        if (!matchedServices.has(bestMatch.name)) {
          matchedServices.set(bestMatch.name, { services: [], confidence: bestMatch.similarity, isNew: false });
        }
        matchedServices.get(bestMatch.name)!.services.push(svc);
        matched = true;
      }
    }

    if (!matched) {
      unmatchedServices.push(svc);
      console.log(`[ServiceImport] Service "${svc.name}" has no match, flagged for category creation`);
    }
  }

  // Step 3: Suggest & create new categories for unmatched services
  if (unmatchedServices.length > 0) {
    const suggestedCats = await suggestCategoriesForUnmatched(unmatchedServices);
    console.log(`[ServiceImport] AI suggested ${suggestedCats.length} new categories`);

    for (const catName of suggestedCats) {
      // Create category in DB
      const [newCat] = await db
        .insert(serviceCategories)
        .values({ name: catName, storeId, sortOrder: 999 })
        .returning({ id: serviceCategories.id });

      console.log(`[ServiceImport] Created new category "${catName}" (id: ${newCat.id})`);

      // Assign unmatched services to new category (simple round-robin for demo)
      if (!matchedServices.has(catName)) {
        matchedServices.set(catName, { services: [], confidence: 0.5, isNew: true });
      }
    }

    // Assign remaining unmatched services to new categories
    const newCats = Array.from(matchedServices.entries())
      .filter(([_, entry]) => entry.isNew)
      .map(([name]) => name);

    for (let i = 0; i < unmatchedServices.length; i++) {
      const catIdx = i % newCats.length;
      const catName = newCats[catIdx];
      matchedServices.get(catName)!.services.push(unmatchedServices[i]);
    }
  }

  // Step 4: Build enriched result
  const enrichedResult: AIMenuResult = {
    categories: Array.from(matchedServices.entries()).map(([categoryName, entry]) => ({
      name: categoryName,
      services: entry.services,
      confidence: entry.confidence,
      isAutoGenerated: entry.isNew,
    })),
  };

  console.log(`[ServiceImport] Enrichment complete: ${enrichedResult.categories.length} categories, ${allServices.length} services`);
  return enrichedResult;
}

// ─── Merge helper — combines two AIMenuResult objects, merging same-name categories ──
function mergeMenuResults(base: AIMenuResult, incoming: AIMenuResult): AIMenuResult {
  const merged = { categories: [...base.categories] };
  for (const inCat of incoming.categories) {
    const existing = merged.categories.find(
      c => c.name.toLowerCase() === inCat.name.toLowerCase()
    );
    if (existing) {
      existing.services = [...existing.services, ...inCat.services];
    } else {
      merged.categories.push(inCat);
    }
  }
  return merged;
}

// ─── Async job processor ───────────────────────────────────────────────────────
async function processImportJob(
  jobId: number,
  storeId: number,
  uploadedFiles: { url: string; originalName: string; mimeType: string }[]
) {
  try {
    await updateJob(jobId, { status: "processing" });

    // Download files from their stored URLs for AI processing
    // Files are already stored in R2 / local — fetch them back as buffers
    const allBuffers: { buffer: Buffer; mimeType: string; originalName: string }[] = [];

    for (const file of uploadedFiles) {
      try {
        // If it's a relative /uploads path (local dev), read from disk
        if (file.url.startsWith("/uploads/")) {
          const fs = await import("fs");
          const path = await import("path");
          const diskPath = path.resolve(process.cwd(), "uploads", file.url.slice("/uploads/".length));
          const buffer = fs.readFileSync(diskPath);
          allBuffers.push({ buffer, mimeType: file.mimeType, originalName: file.originalName });
        } else {
          // Fetch from R2 public URL
          const res = await fetch(file.url);
          if (!res.ok) throw new Error(`Failed to fetch ${file.url}: ${res.status}`);
          const arrayBuffer = await res.arrayBuffer();
          allBuffers.push({
            buffer: Buffer.from(arrayBuffer),
            mimeType: file.mimeType,
            originalName: file.originalName,
          });
        }
      } catch (fetchErr: any) {
        console.warn(`[ServiceImport] Could not re-fetch file ${file.url}:`, fetchErr.message);
      }
    }

    if (allBuffers.length === 0) {
      throw new Error("No files could be loaded for AI processing");
    }

    // Route PDFs through GPT-5.5 (native PDF understanding).
    // Images use GPT-4o (vision). If the upload is a mix, run both and merge.
    const pdfBuffers   = allBuffers.filter(f => f.mimeType === "application/pdf");
    const imageBuffers = allBuffers.filter(f => f.mimeType !== "application/pdf");

    let result: AIMenuResult = { categories: [] };

    if (pdfBuffers.length > 0) {
      console.log(`[ServiceImport] Processing ${pdfBuffers.length} PDF(s) with GPT-5.5…`);
      // Process each PDF separately and merge categories
      for (const pdf of pdfBuffers) {
        const pdfResult = await extractServicesFromPDF(pdf.buffer, pdf.originalName);
        result = mergeMenuResults(result, pdfResult);
      }
    }

    if (imageBuffers.length > 0) {
      console.log(`[ServiceImport] Processing ${imageBuffers.length} image(s) with GPT-4o…`);
      const imgResult = await extractServicesFromImages(imageBuffers);
      result = mergeMenuResults(result, imgResult);
    }

    // ─── NEW: Enrich with intelligent category matching ────────────────────────
    console.log(`[ServiceImport] Running category enrichment for store ${storeId}…`);
    result = await enrichAIResultWithCategoryMatching(result, storeId);
    // ─────────────────────────────────────────────────────────────────────────────

    await updateJob(jobId, {
      status: "completed",
      ai_result: JSON.stringify(result),
      completed_at: new Date().toISOString(),
    });

    // Send success email (fire-and-forget)
    const owner = await getStoreOwnerContact(storeId);
    if (owner) {
      const categoryCount = result.categories.length;
      const serviceCount = result.categories.reduce((acc, c) => acc + c.services.length, 0);
      await sendServiceImportSuccessEmail(
        owner.email,
        owner.firstName ?? "there",
        owner.storeName,
        categoryCount,
        serviceCount
      ).catch((e: any) => console.warn("[ServiceImport] Email failed:", e.message));

      await pool
        .query(`UPDATE service_import_jobs SET notified_at = NOW() WHERE id = $1`, [jobId])
        .catch(() => {});
    }
  } catch (err: any) {
    console.error(`[ServiceImport] Job ${jobId} failed:`, err.message);

    // Classify error for friendly messaging
    let friendlyError = err.message ?? "Unknown error";
    if (/json/i.test(friendlyError) || /parse/i.test(friendlyError)) {
      friendlyError =
        "The AI could not read a structured menu from your photos. The images may have been blurry, contained glare, or the prices were not clearly visible. Please try uploading clearer photos.";
    } else if (/api key/i.test(friendlyError)) {
      friendlyError = "AI processing is temporarily unavailable. Please try again later or add your services manually.";
    }

    await updateJob(jobId, {
      status: "failed",
      error_message: friendlyError,
      completed_at: new Date().toISOString(),
    });

    // Send failure email
    const owner = await getStoreOwnerContact(storeId);
    if (owner) {
      await sendServiceImportFailureEmail(
        owner.email,
        owner.firstName ?? "there",
        owner.storeName,
        friendlyError
      ).catch((e: any) => console.warn("[ServiceImport] Failure email failed:", e.message));
    }
  }
}

// ─── Routes ───────────────────────────────────────────────────────────────────

/**
 * POST /api/service-import/upload
 * Accepts up to 10 images or 1 PDF. Creates job + fires async AI processing.
 */
router.post(
  "/upload",
  (req, res, next) => {
    menuUpload.array("files", 10)(req, res, (err) => {
      if (err instanceof multer.MulterError) {
        return res.status(400).json({ error: `Upload error: ${err.message}` });
      } else if (err) {
        return res.status(400).json({ error: err.message });
      }
      next();
    });
  },
  async (req: Request, res: Response): Promise<void> => {
    const storeId = await requireStore(req, res);
    if (!storeId) return;

    const files = (req.files as Express.Multer.File[]) ?? [];
    const importType = (req.body.importType as string) ?? "photos";

    if (files.length === 0) {
      res.status(400).json({ error: "No files uploaded" });
      return;
    }

    // Upload all files to R2
    const uploadedFiles: { url: string; originalName: string; mimeType: string }[] = [];

    for (const file of files) {
      try {
        const url = await uploadToR2(
          file.buffer,
          `service-import/${storeId}`,
          file.originalname,
          file.mimetype
        );
        uploadedFiles.push({
          url,
          originalName: file.originalname,
          mimeType: file.mimetype,
        });
      } catch (e: any) {
        console.error("[ServiceImport] Upload failed:", e.message);
        res.status(500).json({ error: "Failed to upload file. Please try again." });
        return;
      }
    }

    // Create job record
    const result = await pool.query(
      `INSERT INTO service_import_jobs (store_id, status, import_type, uploaded_files)
       VALUES ($1, 'pending', $2, $3)
       RETURNING id`,
      [storeId, importType, JSON.stringify(uploadedFiles)]
    );
    const jobId: number = result.rows[0].id;

    // Fire async AI processing — do NOT await
    setImmediate(() => {
      processImportJob(jobId, storeId, uploadedFiles).catch((e: any) =>
        console.error("[ServiceImport] Async processor crashed:", e.message)
      );
    });

    res.status(201).json({
      jobId,
      message: "Your menu has been received. Certxa is creating your services in the background.",
      filesUploaded: uploadedFiles.length,
    });
  }
);

/**
 * GET /api/service-import/jobs
 * List all import jobs for the current store.
 */
router.get("/jobs", async (req: Request, res: Response): Promise<void> => {
  const storeId = await requireStore(req, res);
  if (!storeId) return;

  const result = await pool.query(
    `SELECT id, status, import_type, uploaded_files, ai_result, error_message, created_at, completed_at
     FROM service_import_jobs
     WHERE store_id = $1
     ORDER BY created_at DESC
     LIMIT 20`,
    [storeId]
  );

  res.json({ jobs: result.rows });
});

/**
 * GET /api/service-import/jobs/:id
 * Get a specific job's status and AI result.
 */
router.get("/jobs/:id", async (req: Request, res: Response): Promise<void> => {
  const storeId = await requireStore(req, res);
  if (!storeId) return;

  const jobId = parseInt(req.params.id as string, 10);
  if (isNaN(jobId)) {
    res.status(400).json({ error: "Invalid job ID" });
    return;
  }

  const job = await getJob(jobId, storeId);
  if (!job) {
    res.status(404).json({ error: "Job not found" });
    return;
  }

  res.json({ job });
});

/**
 * PATCH /api/service-import/jobs/:id/result
 * Owner edits the AI result before publishing (update ai_result JSON).
 */
router.patch("/jobs/:id/result", async (req: Request, res: Response): Promise<void> => {
  const storeId = await requireStore(req, res);
  if (!storeId) return;

  const jobId = parseInt(req.params.id as string, 10);
  if (isNaN(jobId)) {
    res.status(400).json({ error: "Invalid job ID" });
    return;
  }

  const job = await getJob(jobId, storeId);
  if (!job) {
    res.status(404).json({ error: "Job not found" });
    return;
  }

  const { aiResult } = req.body;
  if (!aiResult || !Array.isArray(aiResult.categories)) {
    res.status(400).json({ error: "Invalid aiResult structure" });
    return;
  }

  await updateJob(jobId, { ai_result: JSON.stringify(aiResult) });
  res.json({ ok: true });
});

/**
 * POST /api/service-import/publish
 * Creates real services from the reviewed AI result.
 * Categories are already created during enrichment (enrichAIResultWithCategoryMatching).
 * This endpoint just creates the service records.
 * Body: { jobId: number, categories: ExtractedCategory[] }
 */
router.post("/publish", async (req: Request, res: Response): Promise<void> => {
  const storeId = await requireStore(req, res);
  if (!storeId) return;

  const { jobId, categories } = req.body as {
    jobId: number;
    categories: ExtractedCategory[];
  };

  if (!Array.isArray(categories) || categories.length === 0) {
    res.status(400).json({ error: "No categories provided" });
    return;
  }

  // Verify job ownership (optional jobId for manual flow where there's no job)
  if (jobId) {
    const job = await getJob(jobId, storeId);
    if (!job) {
      res.status(404).json({ error: "Job not found" });
      return;
    }
  }

  let totalServices = 0;
  let autoGeneratedCategories: string[] = [];

  for (const cat of categories) {
    if (!cat.name?.trim() || !Array.isArray(cat.services) || cat.services.length === 0) {
      continue;
    }

    const categoryName = cat.name.trim();

    // Track which categories were auto-generated
    if (cat.isAutoGenerated) {
      autoGeneratedCategories.push(categoryName);
    }

    // Find the category (should exist from enrichment phase)
    const [existingCat] = await db
      .select({ id: serviceCategories.id })
      .from(serviceCategories)
      .where(
        sql`store_id = ${storeId} AND lower(name) = lower(${categoryName})`
      )
      .limit(1);

    if (!existingCat) {
      // Category doesn't exist — shouldn't happen if enrichment worked correctly, but handle gracefully
      console.warn(`[ServiceImport] Category "${categoryName}" not found for store ${storeId}, skipping`);
      continue;
    }

    // Create services under this category
    for (const svc of cat.services) {
      if (!svc.name?.trim()) continue;
      const price = String(Math.max(0, Number(svc.price) || 0));
      const duration = Math.max(15, Number(svc.duration) || 60);

      // AI-imported services start as inactive drafts — the owner reviews and activates them
      await db.insert(services).values({
        name:        svc.name.trim(),
        price,
        duration,
        category:    categoryName,
        categoryId:  existingCat.id,
        storeId,
        isActive:    false,
        description: svc.description ?? null,
      });

      totalServices++;
    }
  }

  // Mark job as published
  if (jobId) {
    await updateJob(jobId, { status: "published" });
  }

  res.json({
    ok: true,
    servicesCreated: totalServices,
    autoGeneratedCategories,
  });
});

export default router;
