 /**
 * Service Import Routes — AI-powered menu import from photos/PDF + manual review.
 *
 * POST /api/service-import/upload       — upload images/PDF, create job, fire async AI
 * GET  /api/service-import/jobs         — list jobs for current store
 * GET  /api/service-import/jobs/:id     — get job status + ai_result
 * PATCH /api/service-import/jobs/:id/result — owner edits draft (patches ai_result)
 * POST /api/service-import/publish      — create real services from reviewed ai_result
 */

import { Router, Request, Response } from "express";
import multer from "multer";
import { db, pool } from "../db";
import { sql, eq } from "drizzle-orm";
import { services, serviceCategories, addons, locations } from "@shared/schema";
import { resolveSessionStoreId } from "../lib/sessionStore";
import { uploadToR2 } from "../lib/r2";
import { autoAssignServiceImages } from "./serviceImages";
import {
  classifyImportedItem,
  detectSalonBusinessType,
  type SalonBusinessType,
} from "../lib/salonServiceTaxonomy";
import {
  getFixedCategoryTemplate,
  getFixedCategoryNames,
  getFixedCategorySortOrder,
  renderFixedCategoryPromptBlock,
  matchFixedCategoryByPattern,
  type FixedCategoryTemplate,
} from "../lib/catalogCategoryTemplates";
import {
  sendServiceImportSuccessEmail,
  sendServiceImportFailureEmail,
  getStoreOwnerContact,
} from "../lib/systemEmails";

const router = Router();

// ─── Auth guard ───────────────────────────────────────────────────────────────
async function requireStore(req: Request, res: Response): Promise<number | null> {
  const storeId = await resolveSessionStoreId(req);
  if (!storeId) {
    res.status(401).json({ error: "Not authenticated" });
    return null;
  }
  return storeId;
}

// ─── Multer: images + PDFs, up to 10 files, 20 MB each ──────────────────────
const menuUpload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 20 * 1024 * 1024, files: 10 },
  fileFilter: (_req, file, cb) => {
    const allowed = [
      "image/jpeg",
      "image/png",
      "image/webp",
      "image/heic",
      "image/heif",
      "image/gif",
      "application/pdf",
    ];
    if (allowed.includes(file.mimetype)) {
      cb(null, true);
    } else {
      cb(new Error("Only images (JPEG/PNG/WebP/HEIC) and PDF files are allowed"));
    }
  },
});

// ─── DB helpers ───────────────────────────────────────────────────────────────
async function getJob(jobId: number, storeId: number) {
  const result = await pool.query(
    `SELECT * FROM service_import_jobs WHERE id = $1 AND store_id = $2 LIMIT 1`,
    [jobId, storeId]
  );
  return result.rows[0] ?? null;
}

async function updateJob(
  jobId: number,
  fields: Record<string, unknown>
) {
  const keys = Object.keys(fields);
  const values = Object.values(fields);
  const setClauses = keys.map((k, i) => `${k} = $${i + 2}`).join(", ");
  await pool.query(
    `UPDATE service_import_jobs SET ${setClauses} WHERE id = $1`,
    [jobId, ...values]
  );
}

// ─── Ensure table exists (startup safety) ─────────────────────────────────────
export async function ensureServiceImportTable() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS service_import_jobs (
      id             SERIAL PRIMARY KEY,
      store_id       INTEGER NOT NULL,
      status         TEXT    NOT NULL DEFAULT 'pending',
      import_type    TEXT    NOT NULL DEFAULT 'photos',
      uploaded_files JSONB   NOT NULL DEFAULT '[]',
      ai_result      JSONB,
      error_message  TEXT,
      created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      completed_at   TIMESTAMPTZ,
      notified_at    TIMESTAMPTZ
    )
  `);
  await pool.query(
    `CREATE INDEX IF NOT EXISTS idx_sij_store_id ON service_import_jobs(store_id)`
  );
}

// ─── AI extraction ────────────────────────────────────────────────────────────

interface ExtractedService {
  name: string;
  price: number;
  duration: number;
  description?: string;
}

interface ExtractedAddon extends ExtractedService {
  addonCategory?: string;
}

interface ExtractedCategory {
  name: string;
  services: ExtractedService[];
  confidence?: number;        // 0.0-1.0 (from AI matching)
  isAutoGenerated?: boolean;  // true if category was created by AI
}

interface AIMenuResult {
  categories: ExtractedCategory[];
  addons?: ExtractedAddon[];
}

async function getStoreCategoryRaw(storeId: number): Promise<string | null> {
  const result = await pool.query("SELECT category FROM locations WHERE id = $1 LIMIT 1", [storeId]);
  return result.rows[0]?.category ?? null;
}

async function getStoreBusinessType(storeId: number): Promise<SalonBusinessType> {
  const raw = await getStoreCategoryRaw(storeId);
  return detectSalonBusinessType(raw);
}

// ─── Fuzzy matching helper for fallback category assignment ───────────────────
function calculateSimilarity(str1: string, str2: string): number {
  const s1 = str1.toLowerCase().trim();
  const s2 = str2.toLowerCase().trim();
  if (s1 === s2) return 1.0;
  
  // Simple Levenshtein distance-based similarity
  const longer = s1.length > s2.length ? s1 : s2;
  const shorter = s1.length > s2.length ? s2 : s1;
  
  if (longer.length === 0) return 1.0;
  
  const editDistance = getEditDistance(longer, shorter);
  return (longer.length - editDistance) / longer.length;
}

function getEditDistance(s1: string, s2: string): number {
  const costs: number[] = [];
  for (let j = 0; j <= s2.length; j++) costs[j] = j;
  
  for (let i = 1; i <= s1.length; i++) {
    let nw = i - 1;
    costs[0] = i;
    for (let j = 1; j <= s2.length; j++) {
      const cj = Math.min(
        1 + Math.min(costs[j], costs[j - 1]),
        nw + (s1[i - 1] === s2[j - 1] ? 0 : 1)
      );
      nw = costs[j];
      costs[j] = cj;
    }
  }
  return costs[s2.length] ?? 0;
}

function getOpenAIConfig(): { apiKey: string; baseURL?: string } {
  const directApiKey = process.env.OPENAI_API_KEY?.trim();
  const integrationApiKey = process.env.AI_INTEGRATIONS_OPENAI_API_KEY?.trim();

  if (directApiKey) return { apiKey: directApiKey };
  if (integrationApiKey) {
    const baseURL = process.env.AI_INTEGRATIONS_OPENAI_BASE_URL?.trim();
    return { apiKey: integrationApiKey, ...(baseURL ? { baseURL } : {}) };
  }

  throw new Error("OpenAI API key is not configured");
}

const SYSTEM_PROMPT = `You are a salon, spa, tattoo, and piercing menu parser. The owner has uploaded photos or a PDF of their price board. Extract every priced bookable service and every priced optional add-on you can identify, and return ONLY valid JSON.

LAYOUT AND CATEGORY-HEADING RULES (VERY IMPORTANT):
- First inspect the visual layout before reading individual prices. Menu category headings are usually larger, colored, centered, underlined, or separated from the service rows, and normally have no price beside them.
- A category heading directly above a group of services owns the services beneath it until the next heading. Preserve that grouping.
- Menus may have multiple side-by-side columns. Treat each column independently: do not attach a service or price from the left column to a heading or price in the right column.
- A heading is not a service. Never create a service from a standalone title such as "Waxing" or "Threading" when it has no price. Use it as the category name for the rows below it.
- Read the category title exactly enough to distinguish categories such as Waxing and Threading, even when they appear in separate columns. If a heading is clear, use that heading rather than guessing from an individual service name.
- A service row normally contains a service name and a nearby numeric price. Keep the name and price from the same row.

CATEGORY GUIDANCE FOR COMMON MENU WORDING:
- "Mani", "Manis", "Manicure", or "Manicures" belong under Manicures.
- "Pedi", "Pedis", "Pedicure", or "Pedicures" belong under Pedicures.
- If one service contains both a mani/manicure term and a pedi/pedicure term (for example "Mani Pedi" or "Manicure & Pedicure"), it belongs under Combos/Combination.
- Nail repairs, cut-downs, soak-offs/removals, new-set fees, shellac, Gelish, and gel polish belong under Enhancements unless the heading clearly indicates a more specific category.
- Callus treatments, sea-salt scrubs, cooling masks, and toe-nail services belong under Pedicures.
- Hand design, nail design, charms, French tips, and similar design services belong under Nail Art.
- When a broad heading such as "Additional Services" contains these recognizable services, categorize each service by the rules above rather than using Additional Services as the category.

Normalize service names to standard nail salon terminology:
- "Gel X" / "Gel-X" / "Gel X Full" / "GelX" → "Gel-X Full Set"
- "Fill Acrylic" / "Acrylic Fill In" / "Fill" (in acrylic context) → "Acrylic Fill"
- "SNS" / "Dipping Powder" / "Dip" → "Dipping Powder"
- "OPI Gel" / "Gel Color" / "Shellac" → "Gel Manicure"
- "Basic" / "Regular" / "Traditional" manicure → "Classic Manicure"
- "Hard Gel" / "Hard Gel Full Set" → "Hard Gel Full Set"
- "Polygel" / "Poly Gel" / "Poly-Gel" → "Polygel Full Set"
- "French" suffix → keep "French" in the name (e.g. "Gel French Manicure")
 - Add-ons, upgrades, enhancements, and optional extras must not become services or categories. Put them in the top-level "addons" array.
 - For nail menus, examples of add-ons include Polish Change, Rhinestones, Gems, Charms, Hot Towels, Extra Massage, and Nail Whitener. Preserve the listed price and estimate duration.
 - For hair, spa, tattoo, or piercing menus, use the same rule: an optional upgrade or extra that is normally attached to a primary service belongs in "addons".
 - Use the visual heading as the service category. Normalize obvious heading variants, but do not invent an "Add-ons" service category.
For duration, estimate in minutes based on service type if not shown (e.g. manicure=45, pedicure=60, acrylic full set=90).
For prices, extract the numeric value only (no $ sign). If a price range is shown (e.g. "$40-50"), use the lower value.
Return ONLY valid JSON with no markdown, no commentary.

JSON format:
{
  "categories": [
    {
      "name": "Manicures",
      "services": [
        { "name": "Classic Manicure", "price": 25, "duration": 45, "description": "" }
      ]
    }
  ],
  "addons": [
    { "name": "Rhinestones", "price": 5, "duration": 5, "description": "" }
  ]
}`;

/**
 * When the store's business type has a fixed category template (see
 * lib/catalogCategoryTemplates.ts), append it to the base system prompt so
 * extraction uses the same category names as the classification step below —
 * the AI already knows the business type from onboarding, so it should never
 * be guessing at category names from scratch.
 */
function buildSystemPrompt(fixedCategoryBlock: string | null): string {
  if (!fixedCategoryBlock) return SYSTEM_PROMPT;
  return `${SYSTEM_PROMPT}\n\n${fixedCategoryBlock}`;
}

/**
 * Extract services from image files using GPT-4o (vision).
 */
async function extractServicesFromImages(
  imageBuffers: { buffer: Buffer; mimeType: string; originalName: string }[],
  fixedCategoryBlock: string | null
): Promise<AIMenuResult> {
  const OpenAI = (await import("openai")).default;
  const openai = new OpenAI(getOpenAIConfig());

  const content: any[] = [
    {
      type: "text",
      text: "Analyze these menu photos spatially. Identify each visually distinct category heading first, then assign every priced service beneath that heading to it. The heading may be larger, colored, centered, or directly above a column of rows. Carefully keep side-by-side columns separate and never treat an unpriced heading as a service. Return structured JSON only.",
    },
  ];

  for (const img of imageBuffers) {
    const base64 = img.buffer.toString("base64");
    const mimeType = img.mimeType.startsWith("image/heic") ? "image/jpeg" : img.mimeType;
    content.push({
      type: "image_url",
      image_url: {
        url: `data:${mimeType};base64,${base64}`,
        detail: "high",
      },
    });
  }

  const completion = await openai.chat.completions.create({
    model: "gpt-4o",
    max_tokens: 4096,
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: buildSystemPrompt(fixedCategoryBlock) },
      { role: "user", content },
    ],
  });

  return parseAIResponse(completion.choices[0]?.message?.content ?? "");
}

/**
 * Extract services from a PDF file using GPT-5.5 with native PDF understanding.
 * The PDF is uploaded to OpenAI's Files API then referenced in the message.
 */
async function extractServicesFromPDF(
  pdfBuffer: Buffer,
  originalName: string,
  fixedCategoryBlock: string | null
): Promise<AIMenuResult> {
  const { default: OpenAI, toFile } = await import("openai");
  const openai = new OpenAI(getOpenAIConfig());

  // Upload the PDF to OpenAI Files API so the model can read it natively
  const file = await openai.files.create({
    file: await toFile(pdfBuffer, originalName, { type: "application/pdf" }),
    purpose: "user_data",
  });

  console.log(`[ServiceImport] Uploaded PDF to OpenAI Files API: ${file.id}`);

  let completion: any;
  try {
    completion = await openai.chat.completions.create({
      model: "gpt-5.5",
      // GPT-5 reasoning models use max_completion_tokens; max_tokens causes
      // the PDF request to fail before the document is processed.
      max_completion_tokens: 8192,
      response_format: { type: "json_object" },
      messages: [
        { role: "system", content: buildSystemPrompt(fixedCategoryBlock) },
        {
          role: "user",
          content: [
            {
              type: "text",
              text: "Analyze this PDF spatially. Identify each visually distinct category heading first, then assign every priced service beneath that heading to it. The heading may be larger, colored, centered, or directly above a column of rows. Carefully keep side-by-side columns separate and never treat an unpriced heading as a service. Return structured JSON only.",
            },
            {
              type: "file",
              file: { file_id: file.id },
            } as any,
          ],
        },
      ],
    });
  } finally {
    // Clean up the uploaded file regardless of success/failure
    await openai.files.delete(file.id).catch((e: any) =>
      console.warn(`[ServiceImport] Could not delete OpenAI file ${file.id}:`, e.message)
    );
  }

  return parseAIResponse(completion.choices[0]?.message?.content ?? "");
}

/**
 * Shared JSON response parser — strips markdown fences and validates structure.
 */
function parseAIResponse(raw: string): AIMenuResult {
  const jsonStr = raw
    .replace(/^```json\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/\s*```\s*$/i, "")
    .trim();

  const parsed = JSON.parse(jsonStr) as AIMenuResult;

  if (!Array.isArray(parsed.categories)) {
    throw new Error("AI returned unexpected structure — missing categories array");
  }

  return parsed;
}

// ─── Category Management & Intelligent Matching ────────────────────────────────

/**
 * Fetch all existing service categories for a store.
 */
async function getExistingCategories(storeId: number): Promise<string[]> {
  const result = await db
    .select({ name: serviceCategories.name })
    .from(serviceCategories)
    .where(sql`store_id = ${storeId}`)
    .orderBy(sql`sort_order ASC`);
  return result.map(r => r.name);
}

/**
 * Use AI to match a service to the best existing category.
 * Returns category name + confidence score (0.0-1.0).
 * Returns null if no good match found.
 */
async function matchServiceToCategory(
  serviceName: string,
  description: string | undefined,
  existingCategories: string[]
): Promise<{ categoryName: string; confidence: number } | null> {
  if (existingCategories.length === 0) return null;

  const OpenAI = (await import("openai")).default;
  const openai = new OpenAI(getOpenAIConfig());

  const categoryList = existingCategories.join(", ");
  const prompt = `You are a salon service categorization expert. Given a service, pick the BEST matching category.

Service: "${serviceName}"
${description ? `Description: "${description}"` : ""}

Available categories: ${categoryList}

Respond with ONLY valid JSON (no markdown):
{
  "category": "CATEGORY_NAME",
  "confidence": 0.95
}

Confidence should be:
- 1.0 if perfect match
- 0.8-0.99 if very likely
- 0.6-0.79 if reasonable fit
- 0.0-0.59 if poor fit or uncertain`;

  try {
    const completion = await openai.chat.completions.create({
      model: "gpt-4o",
      max_tokens: 100,
      response_format: { type: "json_object" },
      messages: [{ role: "user", content: prompt }],
    });

    const responseText = completion.choices[0]?.message?.content ?? "{}";
    const parsed = JSON.parse(responseText) as { category: string; confidence: number };
    
    // Validate category is in the list
    const isValid = existingCategories.some(c => c.toLowerCase() === parsed.category.toLowerCase());
    if (!isValid) return null;

    return {
      categoryName: parsed.category,
      confidence: Math.min(1.0, Math.max(0.0, parsed.confidence ?? 0)),
    };
  } catch (err: any) {
    console.warn(`[ServiceImport] AI matching failed for "${serviceName}":`, err.message);
    return null;
  }
}

/**
 * Suggest new category names for unmatched services.
 * Returns array of suggested category names (3-5 suggestions).
 */
async function suggestCategoriesForUnmatched(
  unmatched: ExtractedService[]
): Promise<string[]> {
  if (unmatched.length === 0) return [];

  const OpenAI = (await import("openai")).default;
  const openai = new OpenAI(getOpenAIConfig());

  const serviceList = unmatched.map(s => `- ${s.name}${s.description ? ` (${s.description})` : ""}`).join("\n");
  const prompt = `You are a salon service categorization expert. These services don't fit any existing category. Suggest 3-5 logical category names to group them.

Services:
${serviceList}

Respond with ONLY valid JSON (no markdown):
{
  "suggestedCategories": ["Category 1", "Category 2", "Category 3"]
}

Guidelines:
- Use clear, professional names
- Make names broad enough to hold multiple related services
- Avoid generic names like "Other" or "Misc"
- Names should be 1-3 words`;

  try {
    const completion = await openai.chat.completions.create({
      model: "gpt-4o",
      max_tokens: 200,
      response_format: { type: "json_object" },
      messages: [{ role: "user", content: prompt }],
    });

    const responseText = completion.choices[0]?.message?.content ?? "{}";
    const parsed = JSON.parse(responseText) as { suggestedCategories?: string[] };
    
    return (parsed.suggestedCategories ?? []).filter(c => c && typeof c === "string").slice(0, 5);
  } catch (err: any) {
    console.warn(`[ServiceImport] Category suggestion failed:`, err.message);
    return [];
  }
}

/**
 * Main orchestration: enrich AI result with intelligent category matching & auto-creation.
 *
 * When the store's business type has a fixed category template (see
 * lib/catalogCategoryTemplates.ts), every service is placed into one of that
 * template's fixed categories — never invented — and a category is only ever
 * created in the DB the first time a service actually needs it (no empty
 * categories are pre-seeded). Business types without a template fall back to
 * the original dynamic behavior unchanged:
 * 1. Fetch existing store categories
 * 2. For each service: try AI matching (Tier 1) → fuzzy matching (Tier 2)
 * 3. Collect unmatched services
 * 4. If unmatched exist: suggest new categories & create them in DB
 * 5. Return enriched result with all services assigned + confidence scores
 */
async function enrichAIResultWithCategoryMatching(
  aiResult: AIMenuResult,
  storeId: number,
  fixedTemplate: FixedCategoryTemplate | null
): Promise<AIMenuResult> {
  console.log(`[ServiceImport] Enriching AI result with category matching for store ${storeId}…`);

  // Step 1: Get existing categories
  const existingCategoryNames = await getExistingCategories(storeId);
  console.log(`[ServiceImport] Found ${existingCategoryNames.length} existing categories`);

  // Step 2: Flatten all services and attempt matching
  const allServices: Array<ExtractedService & { originalCategory: string }> = [];
  for (const cat of aiResult.categories) {
    for (const svc of cat.services) {
      allServices.push({
        ...svc,
        originalCategory: cat.name,
      });
    }
  }

  const matchedServices: Map<string, { services: ExtractedService[]; confidence: number; isNew: boolean }> = new Map();
  const unmatchedServices: ExtractedService[] = [];
  const extractedAddons: ExtractedAddon[] = [];
  const forcedCategoriesCreated = new Set<string>();
  const businessType = await getStoreBusinessType(storeId);

  // Accept an AI-produced top-level add-ons array as well as rows that the
  // deterministic classifier finds inside category groups.
  for (const addon of aiResult.addons ?? []) {
    if (!addon?.name?.trim()) continue;
    const taxonomy = classifyImportedItem(addon.name, businessType);
    extractedAddons.push({
      ...addon,
      name: taxonomy.normalizedName,
      addonCategory: taxonomy.addonCategory,
    });
  }

  // ── Fixed-template path ──────────────────────────────────────────────────
  // The business type is already known from onboarding, so when a template
  // exists for it, every non-addon service is placed into one of its fixed
  // categories — Tier 0 (pattern rules) → Tier 1 (AI match) → Tier 2 (fuzzy
  // match, no threshold — the fixed list is small enough that the closest
  // one is always an acceptable placement). Categories are created lazily,
  // case-insensitively deduped against the DB, and get the template's sort
  // order — never a new/invented category name.
  if (fixedTemplate) {
    const allowedNames = getFixedCategoryNames(fixedTemplate);
    console.log(`[ServiceImport] Fixed category template active for "${fixedTemplate.businessType}" — allowed categories: ${allowedNames.join(", ")}`);

    const categoryCreationCache = new Map<string, { name: string; isNew: boolean }>();
    const ensureCategory = async (name: string, sortOrder: number): Promise<{ name: string; isNew: boolean }> => {
      const key = name.trim().toLowerCase();
      const cached = categoryCreationCache.get(key);
      if (cached) return cached;

      const existing = await db
        .select({ name: serviceCategories.name })
        .from(serviceCategories)
        .where(sql`store_id = ${storeId} AND lower(name) = lower(${name})`)
        .limit(1);

      if (existing.length) {
        const result = { name: existing[0].name, isNew: false };
        categoryCreationCache.set(key, result);
        return result;
      }

      const [inserted] = await db
        .insert(serviceCategories)
        .values({ name, storeId, sortOrder })
        .returning({ name: serviceCategories.name });
      const result = { name: inserted?.name ?? name, isNew: true };
      categoryCreationCache.set(key, result);
      console.log(`[ServiceImport] Created fixed category "${result.name}" (sortOrder: ${sortOrder})`);
      return result;
    };

    for (const svc of allServices) {
      const taxonomy = classifyImportedItem(svc.name, businessType);
      if (taxonomy.isAddon) {
        extractedAddons.push({
          ...svc,
          name: taxonomy.normalizedName,
          addonCategory: taxonomy.addonCategory,
        });
        console.log(`[ServiceImport] Classified "${svc.name}" as ${taxonomy.addonCategory}`);
        continue;
      }

      let targetName: string | null = matchFixedCategoryByPattern(fixedTemplate, svc.name);
      let confidence = 1;

      if (!targetName) {
        const aiMatch = await matchServiceToCategory(svc.name, svc.description, allowedNames);
        if (aiMatch) {
          targetName = aiMatch.categoryName;
          confidence = aiMatch.confidence;
          console.log(`[ServiceImport] Service "${svc.name}" AI-matched to fixed category "${targetName}" (confidence: ${confidence})`);
        }
      }

      if (!targetName) {
        // Guaranteed fallback — allowedNames is never empty, so this always
        // resolves. There is no "unmatched" outcome for a fixed template:
        // Rule 1 (never invent categories) means every service must land in
        // the closest one of the fixed set, even at low confidence.
        let bestMatch: { name: string; similarity: number } | null = null;
        for (const catName of allowedNames) {
          const similarity = calculateSimilarity(svc.name, catName);
          if (!bestMatch || similarity > bestMatch.similarity) bestMatch = { name: catName, similarity };
        }
        targetName = bestMatch!.name;
        confidence = bestMatch!.similarity;
        console.log(`[ServiceImport] Service "${svc.name}" had no confident match — placed in closest fixed category "${targetName}" (similarity: ${confidence})`);
      }

      const sortOrder = getFixedCategorySortOrder(fixedTemplate, targetName);
      const { name: categoryName, isNew: categoryIsNew } = await ensureCategory(targetName, sortOrder);
      const entry = matchedServices.get(categoryName) ?? { services: [], confidence, isNew: categoryIsNew };
      entry.services.push(svc);
      entry.confidence = (entry.confidence + confidence) / 2;
      matchedServices.set(categoryName, entry);
    }

    // No Step 3 here — fixed templates never invent new categories, and a
    // category that had zero matching services was simply never created.
    const enrichedResult: AIMenuResult = {
      categories: Array.from(matchedServices.entries()).map(([categoryName, entry]) => ({
        name: categoryName,
        services: entry.services,
        confidence: entry.confidence,
        isAutoGenerated: entry.isNew,
      })),
      addons: extractedAddons,
    };
    console.log(`[ServiceImport] Enrichment complete (fixed template): ${enrichedResult.categories.length} categories, ${allServices.length - extractedAddons.length} services, ${extractedAddons.length} add-ons`);
    return enrichedResult;
  }

  // ── Legacy dynamic path (business types with no fixed template) ─────────
  // These two words are reliable category signals and should take precedence
  // over the probabilistic category matcher. A combined manicure + pedicure is
  // always a combo, never two separate categories.
  const getForcedCategory = (serviceName: string, heading: string): { name: string; aliases: string[] } | null => {
    const hasManicure = /\b(?:manis?|manicures?)\b/i.test(serviceName);
    const hasPedicure = /\b(?:pedis?|pedicures?)\b/i.test(serviceName);
    if (hasManicure && hasPedicure) return { name: "Combos", aliases: ["combo", "combos", "combination", "combinations"] };
    if (hasManicure) return { name: "Manicures", aliases: ["manicures", "manicure"] };
    if (hasPedicure) return { name: "Pedicures", aliases: ["pedicures", "pedicure"] };

    // Common short names and add-ons often appear under a broad heading such
    // as "Additional Services". Classify those rows by what the service does
    // instead of leaving them in that catch-all heading.
    const name = serviceName.toLowerCase();
    if (/\b(?:callus|sea salt|cooling mask|toe nails?)\b/.test(name)) {
      return { name: "Pedicures", aliases: ["pedicures", "pedicure"] };
    }
    if (/\b(?:nail repair|cut down|soak off|removal|new set|shellac|gelish|gel polish)\b/.test(name)) {
      return { name: "Enhancements", aliases: ["enhancements", "enhancement"] };
    }
    if (/\b(?:hand design|nail design|charms?|french)\b/.test(name)) {
      return { name: "Nail Art", aliases: ["nail art", "nailart"] };
    }
    if (/\b(?:polish change|trim nails?)\b/.test(name)) {
      return { name: "Manicures", aliases: ["manicures", "manicure"] };
    }

    // The extracted category name represents the visual heading above this
    // row. Prefer it for ambiguous names such as Eyebrows, Lip, or Chin,
    // which can legitimately belong to Waxing or Threading depending on the
    // column they came from.
    const normalizedHeading = heading.trim().toLowerCase().replace(/[&_-]/g, " ").replace(/\s+/g, " ");
    const headingAliases: Record<string, { name: string; aliases: string[] }> = {
      waxing: { name: "Waxing", aliases: ["waxing", "wax"] },
      wax: { name: "Waxing", aliases: ["waxing", "wax"] },
      threading: { name: "Threading", aliases: ["threading", "thread"] },
      thread: { name: "Threading", aliases: ["threading", "thread"] },
      manicures: { name: "Manicures", aliases: ["manicures", "manicure"] },
      manicure: { name: "Manicures", aliases: ["manicures", "manicure"] },
      pedicures: { name: "Pedicures", aliases: ["pedicures", "pedicure"] },
      pedicure: { name: "Pedicures", aliases: ["pedicures", "pedicure"] },
      enhancements: { name: "Enhancements", aliases: ["enhancements", "enhancement"] },
      "nail art": { name: "Nail Art", aliases: ["nail art", "nailart"] },
      combos: { name: "Combos", aliases: ["combos", "combo", "combination", "combinations"] },
      combo: { name: "Combos", aliases: ["combos", "combo", "combination", "combinations"] },
      combination: { name: "Combos", aliases: ["combos", "combo", "combination", "combinations"] },
    };
    return headingAliases[normalizedHeading] ?? null;
  };

  const ensureForcedCategory = async (forced: { name: string; aliases: string[] }): Promise<string> => {
    const existingName = existingCategoryNames.find((name) =>
      forced.aliases.includes(name.trim().toLowerCase())
    );
    if (existingName) return existingName;

    const [newCategory] = await db
      .insert(serviceCategories)
      .values({ name: forced.name, storeId, sortOrder: 999 })
      .returning({ name: serviceCategories.name });
    const categoryName = newCategory?.name ?? forced.name;
    existingCategoryNames.push(categoryName);
    forcedCategoriesCreated.add(categoryName);
    return categoryName;
  };

  for (const svc of allServices) {
    const taxonomy = classifyImportedItem(svc.name, businessType);
    if (taxonomy.isAddon) {
      extractedAddons.push({
        ...svc,
        name: taxonomy.normalizedName,
        addonCategory: taxonomy.addonCategory,
      });
      console.log(`[ServiceImport] Classified "${svc.name}" as ${taxonomy.addonCategory}`);
      continue;
    }
    let matched = false;

    const forcedCategory = getForcedCategory(svc.name, svc.originalCategory);
    if (forcedCategory) {
      const categoryName = await ensureForcedCategory(forcedCategory);
      const entry = matchedServices.get(categoryName) ?? {
        services: [],
        confidence: 1,
        isNew: forcedCategoriesCreated.has(categoryName),
      };
      entry.services.push(svc);
      matchedServices.set(categoryName, entry);
      console.log(`[ServiceImport] Rule-matched service "${svc.name}" to "${categoryName}"`);
      continue;
    }

    // Tier 1: Try AI matching
    if (existingCategoryNames.length > 0) {
      const aiMatch = await matchServiceToCategory(svc.name, svc.description, existingCategoryNames);
      if (aiMatch && aiMatch.confidence >= 0.85) {
        console.log(`[ServiceImport] Service "${svc.name}" matched to "${aiMatch.categoryName}" (confidence: ${aiMatch.confidence})`);
        if (!matchedServices.has(aiMatch.categoryName)) {
          matchedServices.set(aiMatch.categoryName, { services: [], confidence: aiMatch.confidence, isNew: false });
        }
        const entry = matchedServices.get(aiMatch.categoryName)!;
        entry.services.push(svc);
        entry.confidence = (entry.confidence + aiMatch.confidence) / 2;
        matched = true;
      }
    }

    // Tier 2: Fallback to fuzzy matching
    if (!matched && existingCategoryNames.length > 0) {
      let bestMatch: { name: string; similarity: number } | null = null;
      for (const catName of existingCategoryNames) {
        const similarity = calculateSimilarity(svc.name, catName);
        if (similarity >= 0.7 && (!bestMatch || similarity > bestMatch.similarity)) {
          bestMatch = { name: catName, similarity };
        }
      }
      if (bestMatch) {
        console.log(`[ServiceImport] Service "${svc.name}" fuzzy-matched to "${bestMatch.name}" (similarity: ${bestMatch.similarity})`);
        if (!matchedServices.has(bestMatch.name)) {
          matchedServices.set(bestMatch.name, { services: [], confidence: bestMatch.similarity, isNew: false });
        }
        matchedServices.get(bestMatch.name)!.services.push(svc);
        matched = true;
      }
    }

    if (!matched) {
      unmatchedServices.push(svc);
      console.log(`[ServiceImport] Service "${svc.name}" has no match, flagged for category creation`);
    }
  }

  // Step 3: Suggest & create new categories for unmatched services
  if (unmatchedServices.length > 0) {
    const suggestedCats = await suggestCategoriesForUnmatched(unmatchedServices);
    if (suggestedCats.length === 0) suggestedCats.push("Other Services");
    console.log(`[ServiceImport] AI suggested ${suggestedCats.length} new categories`);

    for (const catName of suggestedCats) {
      // Create category in DB
      const [newCat] = await db
        .insert(serviceCategories)
        .values({ name: catName, storeId, sortOrder: 999 })
        .returning({ id: serviceCategories.id });

      console.log(`[ServiceImport] Created new category "${catName}" (id: ${newCat.id})`);

      // Assign unmatched services to new category (simple round-robin for demo)
      if (!matchedServices.has(catName)) {
        matchedServices.set(catName, { services: [], confidence: 0.5, isNew: true });
      }
    }

    // Assign remaining unmatched services to new categories
    const newCats = Array.from(matchedServices.entries())
      .filter(([_, entry]) => entry.isNew)
      .map(([name]) => name);

    for (let i = 0; i < unmatchedServices.length; i++) {
      const catIdx = i % newCats.length;
      const catName = newCats[catIdx];
      matchedServices.get(catName)!.services.push(unmatchedServices[i]);
    }
  }

  // Step 4: Build enriched result
  const enrichedResult: AIMenuResult = {
    categories: Array.from(matchedServices.entries()).map(([categoryName, entry]) => ({
      name: categoryName,
      services: entry.services,
      confidence: entry.confidence,
      isAutoGenerated: entry.isNew,
    })),
    addons: extractedAddons,
  };

  console.log(`[ServiceImport] Enrichment complete: ${enrichedResult.categories.length} categories, ${allServices.length - extractedAddons.length} services, ${extractedAddons.length} add-ons`);
  return enrichedResult;
}

// ─── Merge helper — combines two AIMenuResult objects, merging same-name categories ──
function mergeMenuResults(base: AIMenuResult, incoming: AIMenuResult): AIMenuResult {
  const merged: AIMenuResult = { categories: [...base.categories], addons: [...(base.addons ?? [])] };
  for (const inCat of incoming.categories) {
    const existing = merged.categories.find(
      c => c.name.toLowerCase() === inCat.name.toLowerCase()
    );
    if (existing) {
      existing.services = [...existing.services, ...inCat.services];
    } else {
      merged.categories.push(inCat);
    }
  }
  merged.addons = [...(merged.addons ?? []), ...(incoming.addons ?? [])];
  return merged;
}

// ─── Async job processor ───────────────────────────────────────────────────────
async function processImportJob(
  jobId: number,
  storeId: number,
  uploadedFiles: { url: string; originalName: string; mimeType: string }[]
) {
  try {
    await updateJob(jobId, { status: "processing" });

    // Download files from their stored URLs for AI processing
    // Files are already stored in R2 / local — fetch them back as buffers
    const allBuffers: { buffer: Buffer; mimeType: string; originalName: string }[] = [];

    for (const file of uploadedFiles) {
      try {
        // If it's a relative /uploads path (local dev), read from disk
        if (file.url.startsWith("/uploads/")) {
          const fs = await import("fs");
          const path = await import("path");
          const diskPath = path.resolve(process.cwd(), "uploads", file.url.slice("/uploads/".length));
          const buffer = fs.readFileSync(diskPath);
          allBuffers.push({ buffer, mimeType: file.mimeType, originalName: file.originalName });
        } else {
          // Fetch from R2 public URL
          const res = await fetch(file.url);
          if (!res.ok) throw new Error(`Failed to fetch ${file.url}: ${res.status}`);
          const arrayBuffer = await res.arrayBuffer();
          allBuffers.push({
            buffer: Buffer.from(arrayBuffer),
            mimeType: file.mimeType,
            originalName: file.originalName,
          });
        }
      } catch (fetchErr: any) {
        console.warn(`[ServiceImport] Could not re-fetch file ${file.url}:`, fetchErr.message);
      }
    }

    if (allBuffers.length === 0) {
      throw new Error("No files could be loaded for AI processing");
    }

    // The business type is already known from onboarding (the very first
    // step) — if it has a fixed category template, use it to steer both
    // extraction and classification so the AI never invents categories.
    const storeCategoryRaw = await getStoreCategoryRaw(storeId);
    const fixedTemplate = getFixedCategoryTemplate(storeCategoryRaw);
    const fixedCategoryBlock = fixedTemplate ? renderFixedCategoryPromptBlock(fixedTemplate) : null;
    if (fixedTemplate) {
      console.log(`[ServiceImport] Fixed category template detected for business type "${storeCategoryRaw}"`);
    }

    // Route PDFs through GPT-5.5 (native PDF understanding).
    // Images use GPT-4o (vision). If the upload is a mix, run both and merge.
    const pdfBuffers   = allBuffers.filter(f => f.mimeType === "application/pdf");
    const imageBuffers = allBuffers.filter(f => f.mimeType !== "application/pdf");

    let result: AIMenuResult = { categories: [] };

    if (pdfBuffers.length > 0) {
      console.log(`[ServiceImport] Processing ${pdfBuffers.length} PDF(s) with GPT-5.5…`);
      // Process each PDF separately and merge categories
      for (const pdf of pdfBuffers) {
        const pdfResult = await extractServicesFromPDF(pdf.buffer, pdf.originalName, fixedCategoryBlock);
        result = mergeMenuResults(result, pdfResult);
      }
    }

    if (imageBuffers.length > 0) {
      console.log(`[ServiceImport] Processing ${imageBuffers.length} image(s) with GPT-4o…`);
      const imgResult = await extractServicesFromImages(imageBuffers, fixedCategoryBlock);
      result = mergeMenuResults(result, imgResult);
    }

    // ─── Enrich with intelligent category matching ─────────────────────────────
    console.log(`[ServiceImport] Running category enrichment for store ${storeId}…`);
    result = await enrichAIResultWithCategoryMatching(result, storeId, fixedTemplate);
    // ─────────────────────────────────────────────────────────────────────────────

    await updateJob(jobId, {
      status: "completed",
      ai_result: JSON.stringify(result),
      completed_at: new Date().toISOString(),
    });

    // Send success email (fire-and-forget)
    const owner = await getStoreOwnerContact(storeId);
    if (owner) {
      const categoryCount = result.categories.length;
      const serviceCount = result.categories.reduce((acc, c) => acc + c.services.length, 0);
      await sendServiceImportSuccessEmail(
        owner.email,
        owner.firstName ?? "there",
        owner.storeName,
        categoryCount,
        serviceCount
      ).catch((e: any) => console.warn("[ServiceImport] Email failed:", e.message));

      await pool
        .query(`UPDATE service_import_jobs SET notified_at = NOW() WHERE id = $1`, [jobId])
        .catch(() => {});
    }
  } catch (err: any) {
    console.error(`[ServiceImport] Job ${jobId} failed:`, err.message);

    // Classify error for friendly messaging
    let friendlyError = err.message ?? "Unknown error";
    if (/json/i.test(friendlyError) || /parse/i.test(friendlyError)) {
      friendlyError =
        "The AI could not read a structured menu from your photos. The images may have been blurry, contained glare, or the prices were not clearly visible. Please try uploading clearer photos.";
    } else if (/api key/i.test(friendlyError)) {
      friendlyError = "AI processing is temporarily unavailable. Please try again later or add your services manually.";
    }

    await updateJob(jobId, {
      status: "failed",
      error_message: friendlyError,
      completed_at: new Date().toISOString(),
    });

    // Send failure email
    const owner = await getStoreOwnerContact(storeId);
    if (owner) {
      await sendServiceImportFailureEmail(
        owner.email,
        owner.firstName ?? "there",
        owner.storeName,
        friendlyError
      ).catch((e: any) => console.warn("[ServiceImport] Failure email failed:", e.message));
    }
  }
}

// ─── Routes ───────────────────────────────────────────────────────────────────

/**
 * POST /api/service-import/upload
 * Accepts up to 10 images or 1 PDF. Creates job + fires async AI processing.
 */
router.post(
  "/upload",
  (req, res, next) => {
    menuUpload.array("files", 10)(req, res, (err) => {
      if (err instanceof multer.MulterError) {
        return res.status(400).json({ error: `Upload error: ${err.message}` });
      } else if (err) {
        return res.status(400).json({ error: err.message });
      }
      next();
    });
  },
  async (req: Request, res: Response): Promise<void> => {
    const storeId = await requireStore(req, res);
    if (!storeId) return;

    const files = (req.files as Express.Multer.File[]) ?? [];
    const importType = (req.body.importType as string) ?? "photos";

    if (files.length === 0) {
      res.status(400).json({ error: "No files uploaded" });
      return;
    }

    // Upload all files to R2
    const uploadedFiles: { url: string; originalName: string; mimeType: string }[] = [];

    for (const file of files) {
      try {
        const url = await uploadToR2(
          file.buffer,
          `service-import/${storeId}`,
          file.originalname,
          file.mimetype
        );
        uploadedFiles.push({
          url,
          originalName: file.originalname,
          mimeType: file.mimetype,
        });
      } catch (e: any) {
        console.error("[ServiceImport] Upload failed:", e.message);
        res.status(500).json({ error: "Failed to upload file. Please try again." });
        return;
      }
    }

    // Create job record
    const result = await pool.query(
      `INSERT INTO service_import_jobs (store_id, status, import_type, uploaded_files)
       VALUES ($1, 'pending', $2, $3)
       RETURNING id`,
      [storeId, importType, JSON.stringify(uploadedFiles)]
    );
    const jobId: number = result.rows[0].id;

    // Fire async AI processing — do NOT await
    setImmediate(() => {
      processImportJob(jobId, storeId, uploadedFiles).catch((e: any) =>
        console.error("[ServiceImport] Async processor crashed:", e.message)
      );
    });

    res.status(201).json({
      jobId,
      message: "Your menu has been received. Certxa is creating your services in the background.",
      filesUploaded: uploadedFiles.length,
    });
  }
);

/**
 * GET /api/service-import/jobs
 * List all import jobs for the current store.
 */
router.get("/jobs", async (req: Request, res: Response): Promise<void> => {
  const storeId = await requireStore(req, res);
  if (!storeId) return;

  const result = await pool.query(
    `SELECT id, status, import_type, uploaded_files, ai_result, error_message, created_at, completed_at
     FROM service_import_jobs
     WHERE store_id = $1
     ORDER BY created_at DESC
     LIMIT 20`,
    [storeId]
  );

  res.json({ jobs: result.rows });
});

/**
 * GET /api/service-import/jobs/:id
 * Get a specific job's status and AI result.
 */
router.get("/jobs/:id", async (req: Request, res: Response): Promise<void> => {
  const storeId = await requireStore(req, res);
  if (!storeId) return;

  const jobId = parseInt(req.params.id as string, 10);
  if (isNaN(jobId)) {
    res.status(400).json({ error: "Invalid job ID" });
    return;
  }

  const job = await getJob(jobId, storeId);
  if (!job) {
    res.status(404).json({ error: "Job not found" });
    return;
  }

  res.json({ job });
});

/**
 * PATCH /api/service-import/jobs/:id/result
 * Owner edits the AI result before publishing (update ai_result JSON).
 */
router.patch("/jobs/:id/result", async (req: Request, res: Response): Promise<void> => {
  const storeId = await requireStore(req, res);
  if (!storeId) return;

  const jobId = parseInt(req.params.id as string, 10);
  if (isNaN(jobId)) {
    res.status(400).json({ error: "Invalid job ID" });
    return;
  }

  const job = await getJob(jobId, storeId);
  if (!job) {
    res.status(404).json({ error: "Job not found" });
    return;
  }

  const { aiResult } = req.body;
  if (!aiResult || !Array.isArray(aiResult.categories)) {
    res.status(400).json({ error: "Invalid aiResult structure" });
    return;
  }

  await updateJob(jobId, { ai_result: JSON.stringify(aiResult) });
  res.json({ ok: true });
});

/**
 * POST /api/service-import/publish
 * Creates real services from the reviewed AI result.
 * Categories are already created during enrichment (enrichAIResultWithCategoryMatching).
 * This endpoint just creates the service records.
 * Body: { jobId: number, categories: ExtractedCategory[] }
 */
router.post("/publish", async (req: Request, res: Response): Promise<void> => {
  const storeId = await requireStore(req, res);
  if (!storeId) return;

  const { jobId, categories } = req.body as {
    jobId: number;
    categories: ExtractedCategory[];
  };

  if (!Array.isArray(categories) || categories.length === 0) {
    res.status(400).json({ error: "No categories provided" });
    return;
  }

  // Verify job ownership (optional jobId for manual flow where there's no job)
  if (jobId) {
    const job = await getJob(jobId, storeId);
    if (!job) {
      res.status(404).json({ error: "Job not found" });
      return;
    }
  }

  let totalServices = 0;
  let totalAddons = 0;
  let autoGeneratedCategories: string[] = [];
  const createdServiceIds: number[] = [];
  const importedAddons = Array.isArray((req.body as any).addons) ? (req.body as any).addons as ExtractedAddon[] : [];

  for (const cat of categories) {
    if (!cat.name?.trim() || !Array.isArray(cat.services) || cat.services.length === 0) {
      continue;
    }

    const categoryName = cat.name.trim();

    // Track which categories were auto-generated
    if (cat.isAutoGenerated) {
      autoGeneratedCategories.push(categoryName);
    }

    // Find the category (should exist from enrichment phase)
    const [existingCat] = await db
      .select({ id: serviceCategories.id })
      .from(serviceCategories)
      .where(
        sql`store_id = ${storeId} AND lower(name) = lower(${categoryName})`
      )
      .limit(1);

    if (!existingCat) {
      // Category doesn't exist — shouldn't happen if enrichment worked correctly, but handle gracefully
      console.warn(`[ServiceImport] Category "${categoryName}" not found for store ${storeId}, skipping`);
      continue;
    }

    // Create services under this category
    for (const svc of cat.services) {
      if (!svc.name?.trim()) continue;
      const price = String(Math.max(0, Number(svc.price) || 0));
      const duration = Math.max(15, Number(svc.duration) || 60);

      // The owner has reviewed these entries on the publish screen, so make them
      // visible in the Services page and available for booking immediately.
      const [createdService] = await db.insert(services).values({
        name:        svc.name.trim(),
        price,
        duration,
        category:    categoryName,
        categoryId:  existingCat.id,
        storeId,
        isActive:    true,
        description: svc.description ?? null,
      }).returning({ id: services.id });

      totalServices++;
      if (createdService?.id) createdServiceIds.push(createdService.id);
    }
  }

  // Add-ons are deliberately stored in the add-ons catalog, not as services
  // and not under a fabricated "Add-ons" service category.
  for (const addon of importedAddons) {
    if (!addon?.name?.trim()) continue;
    await db.insert(addons).values({
      name: addon.name.trim(),
      price: String(Math.max(0, Number(addon.price) || 0)),
      duration: Math.max(0, Number(addon.duration) || 0),
      description: addon.description ?? null,
      storeId,
      isActive: true,
    });
    totalAddons++;
  }

  // Match each newly published service to the closest active image in the
  // service image library. This is best-effort so a missing image library can
  // never prevent the service import from completing.
  let imagesAssigned = 0;
  try {
    imagesAssigned = await autoAssignServiceImages(storeId, createdServiceIds);
  } catch (error: any) {
    console.warn(`[ServiceImport] Automatic service image matching skipped: ${error?.message ?? error}`);
  }

  // Mark job as published
  if (jobId) {
    await updateJob(jobId, { status: "published" });
  }

  res.json({
    ok: true,
    servicesCreated: totalServices,
    addonsCreated: totalAddons,
    imagesAssigned,
    autoGeneratedCategories,
  });
});

export default router;
