// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/contractor-payouts/CheckGeneration.tsx": () => import("../components/mockups/contractor-payouts/CheckGeneration.tsx"),
  "./components/mockups/contractor-payouts/Contractors.tsx": () => import("../components/mockups/contractor-payouts/Contractors.tsx"),
  "./components/mockups/contractor-payouts/Ledger.tsx": () => import("../components/mockups/contractor-payouts/Ledger.tsx"),
  "./components/mockups/contractor-payouts/Overview.tsx": () => import("../components/mockups/contractor-payouts/Overview.tsx"),
  "./components/mockups/contractor-payouts/RunPayouts.tsx": () => import("../components/mockups/contractor-payouts/RunPayouts.tsx"),
  "./components/mockups/hero-video/HeroVideoPreview.tsx": () => import("../components/mockups/hero-video/HeroVideoPreview.tsx")
};
