#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Certxa — Redis Setup Script for VPS
#
# Assumes Redis is already installed (apt/yum/pacman).
# Run as root or with sudo privileges.
#
# Usage:
#   chmod +x scripts/setup-redis.sh
#   sudo bash scripts/setup-redis.sh
#
# What this script does:
#   1. Verifies Redis is installed and the redis-server binary is present
#   2. Writes a production-hardened /etc/redis/redis.conf (or patches the
#      existing one) — disables public access, enables persistence, sets
#      maxmemory policy
#   3. Creates a strong auth password (or uses REDIS_PASSWORD env var if set)
#   4. Enables and starts the redis.service systemd unit
#   5. Tests the connection and writes the REDIS_URL to .env.redis (sourced
#      separately or merged into your main .env)
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'
NC='\033[0m'
info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── 0. Require root ───────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  error "Run this script as root: sudo bash scripts/setup-redis.sh"
fi

# ── 1. Verify Redis is installed ──────────────────────────────────────────────
info "Checking for redis-server binary..."
if ! command -v redis-server &>/dev/null; then
  error "redis-server not found. Install Redis first:\n  Ubuntu/Debian: apt install redis-server\n  RHEL/CentOS:   yum install redis\n  Arch:          pacman -S redis"
fi
REDIS_VERSION=$(redis-server --version | awk '{print $3}' | cut -d= -f2)
ok "Redis ${REDIS_VERSION} found at $(command -v redis-server)"

# ── 2. Determine config file location ─────────────────────────────────────────
REDIS_CONF=""
for candidate in /etc/redis/redis.conf /etc/redis.conf /usr/local/etc/redis.conf; do
  if [[ -f "$candidate" ]]; then
    REDIS_CONF="$candidate"
    break
  fi
done

if [[ -z "$REDIS_CONF" ]]; then
  REDIS_CONF="/etc/redis/redis.conf"
  mkdir -p "$(dirname "$REDIS_CONF")"
  warn "No existing redis.conf found — creating $REDIS_CONF"
fi
info "Using config: $REDIS_CONF"

# ── 3. Generate or accept a password ──────────────────────────────────────────
if [[ -z "${REDIS_PASSWORD:-}" ]]; then
  REDIS_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
  info "Generated a random Redis password (stored in .env.redis)"
else
  info "Using REDIS_PASSWORD from environment"
fi

# ── 4. Write hardened Redis config ────────────────────────────────────────────
info "Writing hardened Redis configuration..."

# Preserve the original if this is the first run
if [[ -f "$REDIS_CONF" ]] && [[ ! -f "${REDIS_CONF}.bak" ]]; then
  cp "$REDIS_CONF" "${REDIS_CONF}.bak"
  info "Original config backed up to ${REDIS_CONF}.bak"
fi

cat > "$REDIS_CONF" <<CONF
# ── Certxa AI Receptionist — Redis configuration ──────────────────────────
# Generated by scripts/setup-redis.sh — $(date -u '+%Y-%m-%d %H:%M UTC')

# Bind only to localhost — never expose Redis publicly
bind 127.0.0.1 ::1
port 6379
protected-mode yes

# Authentication
requirepass ${REDIS_PASSWORD}

# Logging
loglevel notice
logfile /var/log/redis/redis-server.log

# Persistence — RDB snapshot (also enables AOF for durability)
save 900 1
save 300 10
save 60 10000
dbfilename dump.rdb
dir /var/lib/redis

appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no

# Memory — 256 MB cap with LRU eviction (safe for availability cache)
maxmemory 256mb
maxmemory-policy allkeys-lru

# Keep cache TTL management sensible for BullMQ
hz 20
dynamic-hz yes

# Connection limits
maxclients 200
tcp-keepalive 300
timeout 0

# Disable dangerous commands in production
rename-command FLUSHALL ""
rename-command FLUSHDB  ""
rename-command CONFIG   ""
rename-command DEBUG    ""
CONF

ok "Redis configuration written to $REDIS_CONF"

# ── 5. Ensure log directory exists ────────────────────────────────────────────
mkdir -p /var/log/redis
chown redis:redis /var/log/redis 2>/dev/null || true

# ── 6. Enable and restart Redis via systemd ────────────────────────────────────
info "Enabling and (re)starting Redis via systemd..."
if systemctl is-enabled redis-server &>/dev/null 2>&1 || systemctl is-enabled redis &>/dev/null 2>&1; then
  SERVICE_NAME=$(systemctl is-enabled redis-server &>/dev/null 2>&1 && echo "redis-server" || echo "redis")
else
  # Try both common service names
  if systemctl list-unit-files | grep -q "redis-server.service"; then
    SERVICE_NAME="redis-server"
  elif systemctl list-unit-files | grep -q "redis.service"; then
    SERVICE_NAME="redis"
  else
    warn "Could not detect Redis systemd service name — trying 'redis-server'"
    SERVICE_NAME="redis-server"
  fi
fi

systemctl enable  "$SERVICE_NAME"
systemctl restart "$SERVICE_NAME"
sleep 2

if systemctl is-active --quiet "$SERVICE_NAME"; then
  ok "Redis service '${SERVICE_NAME}' is running"
else
  error "Redis service failed to start. Check: journalctl -u ${SERVICE_NAME} -n 30"
fi

# ── 7. Smoke test ─────────────────────────────────────────────────────────────
info "Testing Redis connection with AUTH..."
PING_RESULT=$(redis-cli -a "$REDIS_PASSWORD" PING 2>/dev/null || echo "FAILED")
if [[ "$PING_RESULT" == "PONG" ]]; then
  ok "Redis responded PONG — connection works"
else
  error "Redis ping failed (got: ${PING_RESULT}). Check the config and service logs."
fi

# ── 8. Write .env.redis ───────────────────────────────────────────────────────
ENV_FILE="$(pwd)/.env.redis"
cat > "$ENV_FILE" <<ENV
# Auto-generated by scripts/setup-redis.sh — $(date -u '+%Y-%m-%d %H:%M UTC')
# Add this to your main .env file or source it in your startup scripts.

REDIS_URL=redis://:${REDIS_PASSWORD}@127.0.0.1:6379
ENV

ok ".env.redis written to $ENV_FILE"

# ── 9. Print next steps ───────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}══════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Redis setup complete!${NC}"
echo -e "${GREEN}══════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Service:    ${YELLOW}${SERVICE_NAME}${NC}"
echo -e "  Config:     ${YELLOW}${REDIS_CONF}${NC}"
echo -e "  Password:   stored in ${YELLOW}.env.redis${NC}"
echo -e "  REDIS_URL:  ${YELLOW}redis://:****@127.0.0.1:6379${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo ""
echo "  1. Add REDIS_URL to your server's environment:"
echo "     cat .env.redis >> .env"
echo "     # — or —"
echo "     export REDIS_URL=\$(grep REDIS_URL .env.redis | cut -d= -f2-)"
echo ""
echo "  2. If using PM2, add REDIS_URL to your ecosystem.config.js env block"
echo "     and run:  pm2 reload certxa-api"
echo ""
echo "  3. If using systemd for the Node app, add to the [Service] section:"
echo "     EnvironmentFile=/path/to/certxa/.env"
echo ""
echo "  4. Restart the Certxa API server so it picks up REDIS_URL"
echo ""
echo "  5. Verify cache is working — make an AI receptionist call and look"
echo "     for '[Redis] Connected' and '[AvailabilityWorker] Worker started'"
echo "     in the API server logs."
echo ""
echo -e "${YELLOW}Security reminder:${NC}"
echo "  - Redis is bound to 127.0.0.1 only — never expose port 6379 publicly"
echo "  - FLUSHALL and CONFIG commands are disabled"
echo "  - Back up .env.redis somewhere safe — it contains the Redis password"
echo ""
