// Static map: US state abbreviation → primary IANA timezone.
// States that straddle multiple time zones are flagged with multiZone:true
// so the caller emits a warn rather than a fail for those edge cases.

export interface StateTzEntry {
  iana: string;
  multiZone?: boolean;
}

export const STATE_TZ_MAP: Record<string, StateTzEntry> = {
  AL: { iana: "America/Chicago" },
  AK: { iana: "America/Anchorage", multiZone: true },
  AZ: { iana: "America/Phoenix" },
  AR: { iana: "America/Chicago" },
  CA: { iana: "America/Los_Angeles" },
  CO: { iana: "America/Denver" },
  CT: { iana: "America/New_York" },
  DE: { iana: "America/New_York" },
  FL: { iana: "America/New_York", multiZone: true },
  GA: { iana: "America/New_York" },
  HI: { iana: "Pacific/Honolulu" },
  ID: { iana: "America/Boise", multiZone: true },
  IL: { iana: "America/Chicago" },
  IN: { iana: "America/Indiana/Indianapolis", multiZone: true },
  IA: { iana: "America/Chicago" },
  KS: { iana: "America/Chicago", multiZone: true },
  KY: { iana: "America/New_York", multiZone: true },
  LA: { iana: "America/Chicago" },
  ME: { iana: "America/New_York" },
  MD: { iana: "America/New_York" },
  MA: { iana: "America/New_York" },
  MI: { iana: "America/Detroit", multiZone: true },
  MN: { iana: "America/Chicago" },
  MS: { iana: "America/Chicago" },
  MO: { iana: "America/Chicago" },
  MT: { iana: "America/Denver" },
  NE: { iana: "America/Chicago", multiZone: true },
  NV: { iana: "America/Los_Angeles" },
  NH: { iana: "America/New_York" },
  NJ: { iana: "America/New_York" },
  NM: { iana: "America/Denver" },
  NY: { iana: "America/New_York" },
  NC: { iana: "America/New_York" },
  ND: { iana: "America/Chicago", multiZone: true },
  OH: { iana: "America/New_York" },
  OK: { iana: "America/Chicago" },
  OR: { iana: "America/Los_Angeles", multiZone: true },
  PA: { iana: "America/New_York" },
  RI: { iana: "America/New_York" },
  SC: { iana: "America/New_York" },
  SD: { iana: "America/Chicago", multiZone: true },
  TN: { iana: "America/Chicago", multiZone: true },
  TX: { iana: "America/Chicago", multiZone: true },
  UT: { iana: "America/Denver" },
  VT: { iana: "America/New_York" },
  VA: { iana: "America/New_York" },
  WA: { iana: "America/Los_Angeles" },
  WV: { iana: "America/New_York" },
  WI: { iana: "America/Chicago" },
  WY: { iana: "America/Denver" },
  DC: { iana: "America/New_York" },
  PR: { iana: "America/Puerto_Rico" },
  GU: { iana: "Pacific/Guam" },
  VI: { iana: "America/St_Thomas" },
};
