<?php
// Auto-generated by Certxa Blog Manager — do not edit manually.
// Slug: how-to-choose-nail-salon-software
// Serving /blog/how-to-choose-nail-salon-software as a real filesystem path for optimal SEO indexing.
$_GET['blog_slug'] = 'how-to-choose-nail-salon-software';
require dirname(__DIR__) . '/article.php';
