<?php
// Auto-generated by Certxa Blog Manager — do not edit manually.
// Slug: self-service-checkin-kiosk-nail-salon
// Serving /blog/self-service-checkin-kiosk-nail-salon as a real filesystem path for optimal SEO indexing.
$_GET['blog_slug'] = 'self-service-checkin-kiosk-nail-salon';
require dirname(__DIR__) . '/article.php';
