<?php
// Auto-generated by Certxa Blog Manager — do not edit manually.
// Article: Salon Booking Website: How to Set One Up in an Afternoon
// Slug: salon-booking-website
// Serving /blog/salon-booking-website as a real filesystem path for optimal SEO indexing.
$_GET['blog_slug'] = 'salon-booking-website';
require dirname(__DIR__) . '/article.php';
