import { useState, useMemo } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { AppLayout } from "@/components/layout/AppLayout";
import { useSelectedStore } from "@/hooks/use-store";
import { apiRequest } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import {
  Languages,
  RefreshCw,
  CheckCircle2,
  Edit3,
  ChevronDown,
  ChevronUp,
  Loader2,
  AlertCircle,
  Search,
  Sparkles,
} from "lucide-react";

type EntityType = "category" | "service" | "addon" | "product";
type LangCode = "es" | "vi" | "zh" | "ko";

interface Translation {
  language: LangCode;
  name: string;
  description: string | null;
  autoGenerated: boolean;
  isEditedByUser: boolean;
  confidenceScore: number | null;
  updatedAt: string;
}

interface EntityRow {
  id: number;
  base_name: string;
  base_description?: string | null;
  language: string | null;
  translated_name: string | null;
  description: string | null;
  auto_generated: boolean | null;
  is_edited_by_user: boolean | null;
  updated_at: string | null;
}

interface StoreTranslations {
  categories: EntityRow[];
  services: EntityRow[];
  addons: EntityRow[];
  products: EntityRow[];
}

const LANGS: { code: LangCode; label: string; flag: string }[] = [
  { code: "es", label: "Spanish", flag: "🇪🇸" },
  { code: "vi", label: "Vietnamese", flag: "🇻🇳" },
  { code: "zh", label: "Chinese", flag: "🇨🇳" },
  { code: "ko", label: "Korean", flag: "🇰🇷" },
];

const TABS: { key: EntityType; label: string }[] = [
  { key: "category", label: "Categories" },
  { key: "service", label: "Services" },
  { key: "addon", label: "Add-ons" },
  { key: "product", label: "Products" },
];

function groupByEntity(rows: EntityRow[]): Map<number, { baseName: string; baseDescription?: string | null; translations: Map<string, EntityRow> }> {
  const map = new Map<number, { baseName: string; baseDescription?: string | null; translations: Map<string, EntityRow> }>();
  for (const row of rows) {
    if (!map.has(row.id)) {
      map.set(row.id, { baseName: row.base_name, baseDescription: row.base_description, translations: new Map() });
    }
    if (row.language) {
      map.get(row.id)!.translations.set(row.language, row);
    }
  }
  return map;
}

function TranslationStatusBadge({ row, lang }: { row: EntityRow | undefined; lang: LangCode }) {
  if (!row || !row.translated_name) {
    return <Badge variant="outline" className="text-xs text-slate-400 border-slate-200">Pending</Badge>;
  }
  if (row.is_edited_by_user) {
    return <Badge variant="outline" className="text-xs text-emerald-600 border-emerald-200 bg-emerald-50">Edited</Badge>;
  }
  if (row.auto_generated) {
    return <Badge variant="outline" className="text-xs text-blue-600 border-blue-200 bg-blue-50"><Sparkles className="w-3 h-3 mr-1" />AI</Badge>;
  }
  return <Badge variant="outline" className="text-xs text-slate-500">—</Badge>;
}

function EntityCard({
  entityType,
  entityId,
  baseName,
  baseDescription,
  translationMap,
  searchQuery,
}: {
  entityType: EntityType;
  entityId: number;
  baseName: string;
  baseDescription?: string | null;
  translationMap: Map<string, EntityRow>;
  searchQuery: string;
}) {
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<Record<string, { name: string; description: string }>>({});
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const saveMutation = useMutation({
    mutationFn: ({ lang, name, description }: { lang: LangCode; name: string; description: string }) =>
      apiRequest("PUT", `/api/translations/${entityType}/${entityId}/${lang}`, { name, description }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/translations/store"] });
      toast({ title: "Translation saved" });
    },
    onError: () => toast({ title: "Failed to save", variant: "destructive" }),
  });

  const regenMutation = useMutation({
    mutationFn: () => apiRequest("POST", `/api/translations/${entityType}/${entityId}/regenerate`, {}),
    onSuccess: () => {
      toast({ title: "Regenerating translations…", description: "AI is translating in the background." });
      setTimeout(() => queryClient.invalidateQueries({ queryKey: ["/api/translations/store"] }), 5000);
    },
    onError: () => toast({ title: "Failed to queue", variant: "destructive" }),
  });

  const startEdit = (lang: LangCode) => {
    const existing = translationMap.get(lang);
    setEditing(prev => ({
      ...prev,
      [lang]: { name: existing?.translated_name ?? baseName, description: existing?.description ?? "" },
    }));
  };

  const cancelEdit = (lang: LangCode) => {
    setEditing(prev => { const n = { ...prev }; delete n[lang]; return n; });
  };

  const save = (lang: LangCode) => {
    const e = editing[lang];
    if (!e?.name?.trim()) return;
    saveMutation.mutate({ lang, name: e.name, description: e.description });
    cancelEdit(lang);
  };

  const covered = LANGS.filter(l => translationMap.get(l.code)?.translated_name).length;
  const total = LANGS.length;

  return (
    <div className="border border-slate-200 rounded-xl overflow-hidden bg-white shadow-sm">
      <button
        className="w-full flex items-center justify-between px-4 py-3 hover:bg-slate-50 transition-colors text-left"
        onClick={() => setOpen(o => !o)}
      >
        <div className="flex items-center gap-3 min-w-0">
          <div className="flex-1 min-w-0">
            <p className="font-medium text-slate-800 text-sm truncate">{baseName}</p>
            {baseDescription && (
              <p className="text-xs text-slate-400 truncate">{baseDescription}</p>
            )}
          </div>
        </div>
        <div className="flex items-center gap-2 shrink-0 ml-3">
          <span className="text-xs text-slate-500 tabular-nums">{covered}/{total} langs</span>
          {covered === total
            ? <CheckCircle2 className="w-4 h-4 text-emerald-500" />
            : <AlertCircle className="w-4 h-4 text-amber-400" />}
          {open ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
        </div>
      </button>

      {open && (
        <div className="border-t border-slate-100">
          <div className="flex justify-end px-4 py-2 bg-slate-50/60 border-b border-slate-100">
            <Button
              size="sm"
              variant="ghost"
              className="text-xs text-slate-500 h-7 gap-1"
              onClick={() => regenMutation.mutate()}
              disabled={regenMutation.isPending}
            >
              {regenMutation.isPending
                ? <Loader2 className="w-3 h-3 animate-spin" />
                : <RefreshCw className="w-3 h-3" />}
              Re-generate all
            </Button>
          </div>

          <div className="divide-y divide-slate-100">
            {LANGS.map(({ code, label, flag }) => {
              const row = translationMap.get(code);
              const isEditing = !!editing[code];

              return (
                <div key={code} className="px-4 py-3">
                  <div className="flex items-center justify-between mb-1.5">
                    <div className="flex items-center gap-2">
                      <span className="text-base leading-none">{flag}</span>
                      <span className="text-xs font-semibold text-slate-700">{label}</span>
                      <TranslationStatusBadge row={row} lang={code} />
                    </div>
                    {!isEditing && (
                      <Button
                        size="sm"
                        variant="ghost"
                        className="h-6 text-xs text-slate-500 gap-1 px-2"
                        onClick={() => startEdit(code)}
                      >
                        <Edit3 className="w-3 h-3" />
                        Edit
                      </Button>
                    )}
                  </div>

                  {isEditing ? (
                    <div className="space-y-2">
                      <Input
                        value={editing[code].name}
                        onChange={e => setEditing(prev => ({ ...prev, [code]: { ...prev[code], name: e.target.value } }))}
                        placeholder="Translated name"
                        className="text-sm h-8"
                      />
                      {baseDescription !== undefined && (
                        <Textarea
                          value={editing[code].description}
                          onChange={e => setEditing(prev => ({ ...prev, [code]: { ...prev[code], description: e.target.value } }))}
                          placeholder="Translated description (optional)"
                          className="text-sm min-h-[60px] resize-none"
                        />
                      )}
                      <div className="flex gap-2">
                        <Button size="sm" className="h-7 text-xs" onClick={() => save(code)} disabled={saveMutation.isPending}>
                          {saveMutation.isPending ? <Loader2 className="w-3 h-3 animate-spin" /> : "Save"}
                        </Button>
                        <Button size="sm" variant="ghost" className="h-7 text-xs" onClick={() => cancelEdit(code)}>Cancel</Button>
                      </div>
                    </div>
                  ) : (
                    <div>
                      {row?.translated_name ? (
                        <>
                          <p className="text-sm text-slate-700">{row.translated_name}</p>
                          {row.description && <p className="text-xs text-slate-400 mt-0.5">{row.description}</p>}
                        </>
                      ) : (
                        <p className="text-xs text-slate-400 italic">Not yet translated</p>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

export default function TranslationsPage() {
  const { selectedStore } = useSelectedStore();
  const [activeTab, setActiveTab] = useState<EntityType>("service");
  const [search, setSearch] = useState("");
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const { data, isLoading } = useQuery<StoreTranslations>({
    queryKey: ["/api/translations/store"],
    enabled: !!selectedStore,
  });

  const regenAllMutation = useMutation({
    mutationFn: () => apiRequest("POST", "/api/translations/store/regenerate-all", {}),
    onSuccess: (d: any) => {
      toast({ title: `Queued ${d?.queued ?? "?"} translation jobs`, description: "AI is translating in the background." });
      setTimeout(() => queryClient.invalidateQueries({ queryKey: ["/api/translations/store"] }), 8000);
    },
    onError: () => toast({ title: "Failed to queue", variant: "destructive" }),
  });

  const rowsForTab = useMemo(() => {
    if (!data) return [];
    const map: Record<EntityType, EntityRow[]> = {
      category: data.categories,
      service: data.services,
      addon: data.addons,
      product: data.products,
    };
    return map[activeTab] ?? [];
  }, [data, activeTab]);

  const grouped = useMemo(() => groupByEntity(rowsForTab), [rowsForTab]);

  const filteredEntries = useMemo(() => {
    const q = search.toLowerCase().trim();
    return Array.from(grouped.entries()).filter(([, e]) =>
      !q || e.baseName.toLowerCase().includes(q)
    );
  }, [grouped, search]);

  const totalCoverage = useMemo(() => {
    if (!data) return { covered: 0, total: 0 };
    const all = [...data.categories, ...data.services, ...data.addons, ...data.products];
    const entityIds = new Set(all.map(r => `${r.id}`));
    let covered = 0;
    let total = 0;
    for (const id of entityIds) {
      const rows = all.filter(r => String(r.id) === id);
      for (const lang of LANGS) {
        total++;
        if (rows.some(r => r.language === lang.code && r.translated_name)) covered++;
      }
    }
    return { covered, total };
  }, [data]);

  return (
    <AppLayout>
      <div className="max-w-3xl mx-auto px-4 py-6">
        {/* Header */}
        <div className="flex items-start justify-between mb-6 gap-3 flex-wrap">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <div className="w-8 h-8 rounded-lg bg-indigo-100 flex items-center justify-center">
                <Languages className="w-4 h-4 text-indigo-600" />
              </div>
              <h1 className="text-xl font-bold text-slate-800">Content Translations</h1>
            </div>
            <p className="text-sm text-slate-500">
              AI-generated translations for your services, categories, add-ons, and products.
            </p>
          </div>
          <Button
            size="sm"
            onClick={() => regenAllMutation.mutate()}
            disabled={regenAllMutation.isPending}
            className="gap-2 bg-indigo-600 hover:bg-indigo-700 text-white shrink-0"
          >
            {regenAllMutation.isPending
              ? <Loader2 className="w-4 h-4 animate-spin" />
              : <Sparkles className="w-4 h-4" />}
            Translate All
          </Button>
        </div>

        {/* Coverage pill */}
        {!isLoading && (
          <div className="flex items-center gap-2 mb-5 p-3 rounded-xl bg-slate-50 border border-slate-200">
            <div className="flex-1 bg-slate-200 rounded-full h-2 overflow-hidden">
              <div
                className="h-2 bg-indigo-500 rounded-full transition-all"
                style={{ width: `${totalCoverage.total ? (totalCoverage.covered / totalCoverage.total) * 100 : 0}%` }}
              />
            </div>
            <span className="text-xs font-semibold text-slate-600 tabular-nums whitespace-nowrap">
              {totalCoverage.covered} / {totalCoverage.total} translations
            </span>
          </div>
        )}

        {/* Language legend */}
        <div className="flex flex-wrap gap-2 mb-5">
          {LANGS.map(l => (
            <div key={l.code} className="flex items-center gap-1 text-xs text-slate-600 bg-white border border-slate-200 rounded-full px-3 py-1">
              <span>{l.flag}</span>
              <span>{l.label}</span>
            </div>
          ))}
        </div>

        {/* Tabs */}
        <div className="flex gap-1 mb-4 bg-slate-100 rounded-xl p-1">
          {TABS.map(tab => (
            <button
              key={tab.key}
              onClick={() => setActiveTab(tab.key)}
              className={`flex-1 text-xs font-semibold py-2 rounded-lg transition-colors ${
                activeTab === tab.key
                  ? "bg-white text-slate-800 shadow-sm"
                  : "text-slate-500 hover:text-slate-700"
              }`}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Search */}
        <div className="relative mb-4">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
          <Input
            placeholder={`Search ${TABS.find(t => t.key === activeTab)?.label.toLowerCase()}…`}
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="pl-9 text-sm"
          />
        </div>

        {/* Entity list */}
        {isLoading ? (
          <div className="flex items-center justify-center py-20">
            <Loader2 className="w-6 h-6 animate-spin text-slate-400" />
          </div>
        ) : filteredEntries.length === 0 ? (
          <div className="text-center py-20 text-slate-400">
            <Languages className="w-10 h-10 mx-auto mb-3 opacity-30" />
            <p className="text-sm">
              {search ? `No results for "${search}"` : `No ${TABS.find(t => t.key === activeTab)?.label.toLowerCase()} found.`}
            </p>
          </div>
        ) : (
          <div className="space-y-2">
            {filteredEntries.map(([entityId, entity]) => (
              <EntityCard
                key={entityId}
                entityType={activeTab}
                entityId={entityId}
                baseName={entity.baseName}
                baseDescription={entity.baseDescription}
                translationMap={entity.translations}
                searchQuery={search}
              />
            ))}
          </div>
        )}
      </div>
    </AppLayout>
  );
}
