// Auto-generated from salon-management-software_pages_2026-09-19.csv
// Generated: 2026-09-19T14:46:44.132Z

export const seoKeywordCorpus = {
  "totalUniqueKeywords": 1499,
  "featured": [
    "house of nails",
    "the nail company",
    "enchanted nails",
    "nirvana nails",
    "lacquer gallery",
    "the little nail room",
    "florida nails",
    "sage nails",
    "7 day spa tempe",
    "et nails",
    "melody nails",
    "mint nail lounge",
    "posh salon durham",
    "union nails in union missouri",
    "little nail room",
    "blush nails and bar",
    "brookfield nail salons wi",
    "gloss bar dc",
    "paris nail salon oxford ms",
    "ridgefield nail bar",
    "the nailery",
    "impression nails",
    "beyond nails and spa",
    "gloss nail studio",
    "heavenly nails tampa fl",
    "jemk nail lounge",
    "jr nails",
    "la na nail lounge",
    "rika nail salon",
    "st nails",
    "td nail spa",
    "vibe nail bar",
    "essence nails & spa",
    "utopia nail & spa kenosha wi",
    "nail studio durham",
    "lady nail",
    "blue lotus shelton",
    "eureka nails eureka mo",
    "happy nail supply",
    "happy nails chicago",
    "la petite nails",
    "le lam nail salon",
    "montana nails",
    "nail salon columbus ms",
    "nails and more salon",
    "nails by jenny",
    "nails by vivian",
    "pure natural nail salon",
    "s&d nails",
    "td nail & bar",
    "xo nails wall nj",
    "nail garden studio city",
    "utopia nails kenosha",
    "knock knock nails",
    "lili nails",
    "maple nails",
    "alameda nails",
    "beautique nail salon",
    "cedar nails",
    "florida nails orlando",
    "gel factory",
    "glow nails and spa",
    "haute nails",
    "hq nails",
    "mason nail bar",
    "me nails salon",
    "nail salon beaufort sc",
    "nail salon perrysburg ohio",
    "nails for today",
    "pansy nails",
    "shirley nails",
    "sparenity",
    "union nails union mo",
    "vino nail bar",
    "71.29 nail studio",
    "glowing nails",
    "sage nail salon",
    "brio nails marlton",
    "utopia 1",
    "amy nails 2",
    "cherie nail spa",
    "chu nails",
    "grace nail",
    "gurnee nails",
    "jess nails",
    "kings nail spa",
    "le lani",
    "luxury nails & spa of lake mary",
    "moonlit nail spa",
    "morrissey nails",
    "muse nail spa",
    "nail bar cambridge",
    "nail salons lima ohio",
    "nails & beyond",
    "nails by andy",
    "posh the salon durham",
    "sage nail spa",
    "you got nails",
    "blue lotus nail salon shelton ct",
    "utopia nails in kenosha wi",
    "lake placid nail salon",
    "bethesda nail salon",
    "hobby nails",
    "josie nail spa",
    "paint nail beauty spa bellevue",
    "sun nails milford ct",
    "utopia nails kenosha wi",
    "apple valley mn nail salons",
    "b's nails",
    "bella nails naperville",
    "bellacures sherman oaks",
    "cherry creek nails",
    "chic happens nails",
    "evolution nail spa",
    "happy nails 2",
    "million dollar nails",
    "nail haven by melissa netcong",
    "nail kitchen - raleigh",
    "nail salon dawsonville ga",
    "nail salon park city utah",
    "nail salon reston town center",
    "nail studio suwanee",
    "nest nails",
    "noble salon tampa",
    "palm beach nails & foot spa okeechobee",
    "polish room 1",
    "raizun",
    "simply polished",
    "spring lake nails",
    "sylmar nail salon",
    "toe paradise arlington heights",
    "wayne nails",
    "wonderland nail spa",
    "dawn nails",
    "utopia kenosha",
    "vo's nails",
    "waterscape nails",
    "city star nails cleveland",
    "lux nail - orland park",
    "mellow nails",
    "nail lab cary",
    "1989 nail bar",
    "5g nails",
    "amor nail lounge",
    "angie nail",
    "astudio nails",
    "ava nail salon",
    "be u nails",
    "best friend nails",
    "beyond nail",
    "beyond nails north wales",
    "bks nails",
    "boca nail bar",
    "boca nail bar boca raton fl",
    "citrine nail bar",
    "cm nails",
    "cosmo nail & beauty supply",
    "dm nails",
    "enails savage",
    "future nail & spa",
    "glam nails sharpsburg",
    "goodlettsville nails",
    "holi nails",
    "impressions nail salon",
    "k&t nails",
    "la nails montrose co",
    "level up lafayette",
    "mt vernon nails",
    "nail bar oxford ms",
    "nail salon brockport ny",
    "nail salon cherry creek",
    "nail salon east brunswick nj",
    "nail salon wellington city",
    "nail spot & spa",
    "nailed it pdx",
    "nails and bubbles",
    "natural nail lounge",
    "natural nail studio",
    "old bag of nails delaware",
    "ramz nails",
    "spotlight nails",
    "susan's nails",
    "today's nail",
    "top nails marshalltown iowa",
    "towson nails salon",
    "tranquility nails & spa bellevue",
    "utopia kenosha wi",
    "aj nails & spa",
    "akoi nail",
    "april nails & spa",
    "k&j nails",
    "maile nails",
    "nailbox salon",
    "nails lashes nyc - russian manicure manhattan",
    "black onyx nail salon",
    "el nail sense",
    "k&n nails",
    "nail bar by isa",
    "nail fix santa clarita",
    "nail lounge at millenia",
    "nail salon la grange",
    "nail salon osage beach mo",
    "nail salons in hinesville ga",
    "nice nails ii",
    "romancing nails salon",
    "sky nails & lash studio highlands ranch",
    "aj nail spa",
    "aki '93 nail spa",
    "artisan nail",
    "ava's nail bar",
    "be u nails bar",
    "bm nails",
    "capital waxing salon washington dc",
    "ch nails",
    "claudia's nails",
    "cupid nails",
    "d and t nails",
    "deko nails",
    "envy nails pittsburgh",
    "everything nails",
    "glossbar dc",
    "her nail salon",
    "jas nails davenport",
    "jojo nails chino",
    "kosmo nails boutique",
    "luminous nail studio",
    "luxe nails overland park",
    "modern nails sandusky ohio",
    "nail 54",
    "nail salon apex",
    "nail salon morehead ky",
    "nail salon mount airy nc",
    "nail salon savage mn",
    "nail studio crown point",
    "nailbox salon and spa",
    "nails 99",
    "nails by mercede orlando",
    "nails sun prairie wi",
    "nailsaholic",
    "perdido nail spa",
    "raizun nail spa",
    "sabrina's nails",
    "sage nail",
    "silk nail spa",
    "star nails warren ohio",
    "surf city nails",
    "sylacauga nails",
    "thao nails",
    "the nail room in pace",
    "the room nail bar islamorada",
    "tin tin nail spa",
    "twisted nailz",
    "utopia nails in west palm beach",
    "waltham nails spa",
    "z&y nail spa",
    "aura nails & spa",
    "cat lynn",
    "glaze nail spa",
    "jos nails",
    "k & j nails",
    "nail salon cottage grove mn",
    "nail salons in east haven ct",
    "nail shop cambridge",
    "sugar polish nail bar midtown",
    "tranquility spa bellevue",
    "urbanchic nailbar cary nc",
    "utopia nails kenosha wisconsin",
    "wooster nail salon",
    "la nails exton",
    "magnifique nail studio",
    "citron organic nail",
    "blue sky nails highlands",
    "kt nails bar",
    "lacquer me nail bar",
    "lumi nails lounge burnsville",
    "nail salons coon rapids minnesota",
    "nail salons in apex nc",
    "305 nails & spa",
    "a vie nails and spa",
    "aj nails town and country",
    "azalea nails",
    "best nails medina oh",
    "cali nails fort wayne indiana",
    "covington nails covington wa",
    "easy beauty space",
    "eco nails & spa",
    "envy ii nails pittsburgh",
    "expert nails willoughby",
    "harvest moon nails",
    "hk nails",
    "inails and lash",
    "it's jamie nail & beauty",
    "jos nails summersville wv",
    "jp nail",
    "jp one nails",
    "kk nail",
    "la belle summerhill",
    "latoue nails",
    "lux nails cleveland tn",
    "luxury nail spa oak park",
    "madeline nails",
    "mandy nails",
    "maplewood nails maplewood mn",
    "mk master nail spa",
    "mt nails woodbury",
    "nail e",
    "nail lounge manalapan",
    "nail salon fairmont wv",
    "nail salon madison nj",
    "nail salon oxford nc",
    "nail salon richmond indiana",
    "nail salons belmar lakewood co",
    "nail salons in mequon",
    "nails beyond",
    "nails by grace",
    "nails by olivia",
    "nails so happy murfreesboro tennessee",
    "natalie nails",
    "salon website builder",
    "she she nail salon"
  ],
  "grouped": {
    "highIntent": [
      "house of nails",
      "the nail company",
      "enchanted nails",
      "nirvana nails",
      "the little nail room",
      "florida nails",
      "sage nails",
      "7 day spa tempe",
      "et nails",
      "melody nails",
      "mint nail lounge",
      "posh salon durham",
      "union nails in union missouri",
      "little nail room",
      "blush nails and bar",
      "brookfield nail salons wi",
      "paris nail salon oxford ms",
      "ridgefield nail bar",
      "impression nails",
      "beyond nails and spa",
      "gloss nail studio",
      "heavenly nails tampa fl",
      "jemk nail lounge",
      "jr nails",
      "la na nail lounge",
      "rika nail salon",
      "st nails",
      "td nail spa",
      "vibe nail bar",
      "essence nails & spa",
      "utopia nail & spa kenosha wi",
      "nail studio durham",
      "lady nail",
      "eureka nails eureka mo",
      "happy nail supply",
      "happy nails chicago",
      "la petite nails",
      "le lam nail salon",
      "montana nails",
      "nail salon columbus ms",
      "nails and more salon",
      "nails by jenny",
      "nails by vivian",
      "pure natural nail salon",
      "s&d nails",
      "td nail & bar",
      "xo nails wall nj",
      "nail garden studio city",
      "utopia nails kenosha",
      "knock knock nails",
      "lili nails",
      "maple nails",
      "alameda nails",
      "beautique nail salon",
      "cedar nails",
      "florida nails orlando",
      "glow nails and spa",
      "haute nails",
      "hq nails",
      "mason nail bar",
      "me nails salon",
      "nail salon beaufort sc",
      "nail salon perrysburg ohio",
      "nails for today",
      "pansy nails",
      "shirley nails",
      "union nails union mo",
      "vino nail bar",
      "71.29 nail studio",
      "glowing nails",
      "sage nail salon",
      "brio nails marlton",
      "amy nails 2",
      "cherie nail spa",
      "chu nails",
      "grace nail",
      "gurnee nails",
      "jess nails",
      "kings nail spa",
      "luxury nails & spa of lake mary",
      "moonlit nail spa",
      "morrissey nails",
      "muse nail spa",
      "nail bar cambridge",
      "nail salons lima ohio",
      "nails & beyond",
      "nails by andy",
      "posh the salon durham",
      "sage nail spa",
      "you got nails",
      "blue lotus nail salon shelton ct",
      "utopia nails in kenosha wi",
      "lake placid nail salon",
      "bethesda nail salon",
      "hobby nails",
      "josie nail spa",
      "paint nail beauty spa bellevue",
      "sun nails milford ct",
      "utopia nails kenosha wi",
      "apple valley mn nail salons",
      "b's nails",
      "bella nails naperville",
      "cherry creek nails",
      "chic happens nails",
      "evolution nail spa",
      "happy nails 2",
      "million dollar nails",
      "nail haven by melissa netcong",
      "nail kitchen - raleigh",
      "nail salon dawsonville ga",
      "nail salon park city utah",
      "nail salon reston town center",
      "nail studio suwanee",
      "nest nails",
      "noble salon tampa",
      "palm beach nails & foot spa okeechobee",
      "spring lake nails",
      "sylmar nail salon",
      "wayne nails",
      "wonderland nail spa",
      "dawn nails",
      "vo's nails",
      "waterscape nails",
      "city star nails cleveland",
      "lux nail - orland park",
      "mellow nails",
      "nail lab cary",
      "1989 nail bar",
      "5g nails",
      "amor nail lounge",
      "angie nail",
      "astudio nails",
      "ava nail salon",
      "be u nails",
      "best friend nails",
      "beyond nail",
      "beyond nails north wales",
      "bks nails",
      "boca nail bar",
      "boca nail bar boca raton fl",
      "citrine nail bar",
      "cm nails",
      "cosmo nail & beauty supply",
      "dm nails",
      "future nail & spa",
      "glam nails sharpsburg",
      "goodlettsville nails",
      "holi nails",
      "impressions nail salon",
      "k&t nails",
      "la nails montrose co",
      "mt vernon nails",
      "nail bar oxford ms",
      "nail salon brockport ny",
      "nail salon cherry creek",
      "nail salon east brunswick nj",
      "nail salon wellington city",
      "nail spot & spa",
      "nails and bubbles",
      "natural nail lounge",
      "natural nail studio",
      "old bag of nails delaware",
      "ramz nails",
      "spotlight nails",
      "susan's nails",
      "today's nail",
      "top nails marshalltown iowa",
      "towson nails salon",
      "tranquility nails & spa bellevue",
      "aj nails & spa",
      "akoi nail",
      "april nails & spa",
      "k&j nails",
      "maile nails",
      "nailbox salon",
      "nails lashes nyc - russian manicure manhattan",
      "black onyx nail salon",
      "el nail sense",
      "k&n nails",
      "nail bar by isa",
      "nail fix santa clarita",
      "nail lounge at millenia",
      "nail salon la grange",
      "nail salon osage beach mo",
      "nail salons in hinesville ga",
      "nice nails ii",
      "romancing nails salon",
      "sky nails & lash studio highlands ranch",
      "aj nail spa",
      "aki '93 nail spa",
      "artisan nail",
      "ava's nail bar",
      "be u nails bar",
      "bm nails",
      "capital waxing salon washington dc",
      "ch nails",
      "claudia's nails",
      "cupid nails",
      "d and t nails",
      "deko nails",
      "envy nails pittsburgh",
      "everything nails",
      "her nail salon",
      "jas nails davenport",
      "jojo nails chino",
      "kosmo nails boutique",
      "luminous nail studio",
      "luxe nails overland park",
      "modern nails sandusky ohio",
      "nail 54",
      "nail salon apex",
      "nail salon morehead ky",
      "nail salon mount airy nc",
      "nail salon savage mn",
      "nail studio crown point",
      "nailbox salon and spa",
      "nails 99",
      "nails by mercede orlando",
      "nails sun prairie wi",
      "perdido nail spa"
    ],
    "localIntent": [
      "union nails in union missouri",
      "brookfield nail salons wi",
      "paris nail salon oxford ms",
      "heavenly nails tampa fl",
      "utopia nail & spa kenosha wi",
      "eureka nails eureka mo",
      "nail salon columbus ms",
      "xo nails wall nj",
      "nail garden studio city",
      "nail salon beaufort sc",
      "union nails union mo",
      "blue lotus nail salon shelton ct",
      "utopia nails in kenosha wi",
      "sun nails milford ct",
      "utopia nails kenosha wi",
      "apple valley mn nail salons",
      "nail salon dawsonville ga",
      "nail salon park city utah",
      "nail salon reston town center",
      "palm beach nails & foot spa okeechobee",
      "city star nails cleveland",
      "lux nail - orland park",
      "boca nail bar boca raton fl",
      "la nails montrose co",
      "nail bar oxford ms",
      "nail salon brockport ny",
      "nail salon east brunswick nj",
      "nail salon wellington city",
      "utopia kenosha wi",
      "nail salon osage beach mo",
      "nail salons in hinesville ga",
      "luxe nails overland park",
      "nail salon morehead ky",
      "nail salon mount airy nc",
      "nail salon savage mn",
      "nails sun prairie wi",
      "surf city nails",
      "the nail room in pace",
      "utopia nails in west palm beach",
      "nail salon cottage grove mn",
      "nail salons in east haven ct",
      "urbanchic nailbar cary nc",
      "nail salons in apex nc",
      "aj nails town and country",
      "best nails medina oh",
      "lux nails cleveland tn",
      "luxury nail spa oak park",
      "maplewood nails maplewood mn",
      "nail salon madison nj",
      "nail salon oxford nc",
      "nail salons belmar lakewood co",
      "nail salons in mequon",
      "nail salons in alabaster",
      "nail salons in blue ridge georgia",
      "nail salons in georgetown ky",
      "nj nails spa novato ca",
      "allure nails columbia md",
      "expert nails galloway nj",
      "nail salons exton pa",
      "nail salon cedar city",
      "brilliant nails toms river nj",
      "eden nail spa leesburg va",
      "elite nails waynesboro pa",
      "enails savage mn",
      "lovely hair and nails lebanon pa",
      "nail bar lounge beaufort sc",
      "nail salon nantucket ma",
      "nail salon wytheville va",
      "nail salons in east haven",
      "nail salons in guntersville alabama",
      "nail salons in new berlin wi",
      "nail salons in shelbyville",
      "nail salons in whiteville north carolina",
      "pristine nail lounge nail salon winter park",
      "simply nails gloucester va",
      "solar nails savage mn",
      "the ct nail lounge",
      "nail salon in spanish fort al",
      "nail salons in cortland",
      "nail salons in la plata md",
      "nail salon jamaica plain ma",
      "nail salons mount prospect il",
      "solar nails shillington pa",
      "z nails woodstock ga",
      "nail salon in hagerstown md",
      "high cotton athens al",
      "3d nail salon waterbury ct",
      "beautiful nails erie pa",
      "bliss nails plainview ny",
      "boynton nails boynton beach fl",
      "just nails nails salon in fountain",
      "lv spa and nails grand junction co",
      "magic nails spa countryside plaza countryside il",
      "metcalf nail lounge overland park ks",
      "montana nails santa monica ca",
      "nail places in gloucester",
      "nail salon chesterfield va",
      "nail salon in muskego wi",
      "nail salon robinson town center",
      "nail salon rocky point ny",
      "nail salon west haven ct",
      "nail salons east brunswick nj",
      "nail salons in diamond bar ca",
      "nail salons in hartselle al",
      "nail salons in lemoyne pa",
      "nail salons in mcmurray pa",
      "nail salons in norristown pa",
      "nails lab ca",
      "paradiso hollister ca",
      "pretty nails fresno ca",
      "q nails burnsville mn",
      "queen city salon and spa",
      "solar nails columbia tn",
      "t nails inver grove heights mn",
      "nail 63 madison wi",
      "nail salons in macclenny florida",
      "nail salons in nantucket",
      "nails and company plymouth mn",
      "winchester ky nail salon",
      "elegance nail & spa naperville il",
      "hollywood nails cocoa beach fl",
      "lux nails lagrange ga",
      "nail salons in mayfield ky",
      "elite nails in brighton colorado",
      "beyond nails apple valley mn",
      "nail salons in poplar bluff mo",
      "nail salons white house tn",
      "nails in park city",
      "1010 n glebe rd arlington va",
      "1010 north glebe road arlington va",
      "301 newbury st danvers ma",
      "bella nails naperville il",
      "city nails aurora",
      "eagle nails havertown pa",
      "euphoria nails norwell ma",
      "fancy nails harmony pa",
      "glitz nail salon franklin wi",
      "in style nails inc",
      "king nails festus mo",
      "lily nails eden nc",
      "nail bar san marcos ca",
      "nail salon fox lake il",
      "nail salon greensboro ga",
      "nail salon hermosa beach ca",
      "nail salon in lakewood nj",
      "nail salon in leland nc",
      "nail salon lafayette tn",
      "nail salon pleasant view tn",
      "nail salons dawsonville ga",
      "nail salons in archdale nc",
      "nail salons in jenkintown pa",
      "nail salons in lawrenceburg ky",
      "nail salons in manitowoc",
      "nail salons in philadelphia ms",
      "nail salons in south boston va",
      "nail shop in fairburn ga",
      "nail studio boynton beach fl",
      "nails and cocktails oxford ms",
      "nails in sun prairie",
      "perfect nails eden prairie mn",
      "q nails vero beach",
      "super nails milltown nj",
      "vip nails dickson tn",
      "blush nails davie fl",
      "chic nails brookfield wi",
      "flawless nails midland park",
      "gel nails boardman oh",
      "kcn nails minneapolis mn",
      "nail bar fort collins co",
      "nail places in oxford ohio",
      "nail salons in white house tennessee",
      "polish nails easton md",
      "nail salon in new windsor ny",
      "nails starkville ms",
      "moon nails apple valley mn",
      "nail salon montgomery village md",
      "nail salon in sun prairie",
      "city nails on the square",
      "liv nails woodbridge nj",
      "nail salon prospect ct",
      "nail salons brookfield ct",
      "nail salons in adairsville ga",
      "6616 s parker rd aurora co",
      "acqua nails bethesda md",
      "all nails sun prairie wi",
      "city nails beaufort",
      "daisy nail salon ventura ca",
      "danville nails ky",
      "divine nail spa leesburg va",
      "e nails savage mn",
      "encore nails boulder co",
      "euphoria norwell ma",
      "fancy nails hagerstown md",
      "grace nails near me",
      "k nails oneida tn",
      "lv spa & nails grand junction co",
      "magic nails newport news va",
      "mia nail spa macomb il",
      "misty nails butler pa",
      "nail salon douglassville pa",
      "nail salon farmingville ny",
      "nail salon in brier creek",
      "nail salon in kennett mo",
      "nail salon in powder springs ga",
      "nail salon newark ny",
      "nail salon union mo",
      "nail salons cottage grove mn",
      "nail salons in falcon colorado",
      "nail salons in franklin lakes nj",
      "nail salons in gallipolis ohio",
      "nail salons in port clinton ohio",
      "nail tech bristol pa",
      "nails and tan garner nc",
      "nails brookfield wi",
      "nails danville ky",
      "nails in towson",
      "nails lehigh acres fl",
      "nails lemont il",
      "nails spa sterling il",
      "neon nails erie pa",
      "ritz nails overland park ks",
      "the posh nail co",
      "top nails forest ms",
      "uptown nails williamsburg va",
      "vv nails carpentersville il",
      "west end nails clayton nc",
      "3d nail spa waterbury ct",
      "jade nails kirksville mo",
      "love nails cleveland tn",
      "lush nails winter park",
      "mj nails derby ct",
      "nail forum near me",
      "nail salon fort atkinson wi",
      "nail salon in creedmoor nc",
      "nail salon in fontana on sierra",
      "nail salons eufaula al",
      "nails 99 in kittanning",
      "nails enterprise al",
      "shiny nails burnsville mn",
      "signature nails greensboro nc",
      "queen nails parkville mo",
      "nail salons in apple valley",
      "beauty in us conshohocken",
      "davis nails in waldorf md",
      "lemon nails stratford ct",
      "mentor nails mentor oh",
      "nail salons hopkinsville ky",
      "nail salons in bluffton sc",
      "nail salons in buckhannon wv",
      "nail salons in knightdale",
      "nails london ky",
      "alans nail spa jacksonville il",
      "alans nails jacksonville il",
      "angel nails royal oak mi",
      "aphrodite nails bayonne nj",
      "bb nails burnsville mn",
      "ben nails and spa coon rapids mn",
      "blooming nails newtown square pa",
      "cali pro nails jensen beach",
      "chic nail spa brookfield wi"
    ],
    "dealIntent": [],
    "serviceIntent": [
      "7 day spa tempe",
      "beyond nails and spa",
      "td nail spa",
      "essence nails & spa",
      "utopia nail & spa kenosha wi",
      "gel factory",
      "glow nails and spa",
      "cherie nail spa",
      "kings nail spa",
      "luxury nails & spa of lake mary",
      "moonlit nail spa",
      "muse nail spa",
      "sage nail spa",
      "josie nail spa",
      "paint nail beauty spa bellevue",
      "evolution nail spa",
      "palm beach nails & foot spa okeechobee",
      "polish room 1",
      "wonderland nail spa",
      "future nail & spa",
      "nail spot & spa",
      "tranquility nails & spa bellevue",
      "aj nails & spa",
      "april nails & spa",
      "nails lashes nyc - russian manicure manhattan",
      "sky nails & lash studio highlands ranch",
      "aj nail spa",
      "aki '93 nail spa",
      "nailbox salon and spa",
      "perdido nail spa",
      "raizun nail spa",
      "silk nail spa",
      "tin tin nail spa",
      "waltham nails spa",
      "z&y nail spa",
      "aura nails & spa",
      "glaze nail spa",
      "sugar polish nail bar midtown",
      "tranquility spa bellevue",
      "305 nails & spa",
      "a vie nails and spa",
      "eco nails & spa",
      "inails and lash",
      "luxury nail spa oak park",
      "mk master nail spa",
      "yeppi nail & spa",
      "nj nails spa novato ca",
      "polish nail boutique",
      "tranquility nails and spa bellevue",
      "fantastique nails & spa",
      "red coral nails & spa",
      "eden nail spa leesburg va",
      "enchanted nail spa",
      "envy ii nail spa",
      "essie nails and spa",
      "ez nails & spa",
      "gardenia nail and spa",
      "hayes nail spa",
      "lee spa nails durham",
      "magic nails spa countryside",
      "nail spa lane montana",
      "narberth nails and spa",
      "dip nail bar the row dana point",
      "allure nail spa columbia",
      "area one nail spa",
      "fleur nails and lashes",
      "methuen nails & lash",
      "western nail spa",
      "happy nails and lashes shoreline",
      "divinity nail spa",
      "nola nails & spa",
      "polished nails & lashes",
      "a vie nails & spa",
      "abby nails & spa",
      "b&b nails spa reviews",
      "e nails & spa shakopee",
      "glam nail & spa",
      "la bonne vie fantastic nail spa",
      "lavo nail & spa",
      "luscious nails & spa",
      "lv spa and nails grand junction co",
      "magic nails spa countryside plaza countryside il",
      "mystic nail spa",
      "nail art llc",
      "pink polish west ashley",
      "polish nails boulder",
      "queen city salon and spa",
      "eden nail spa leesburg",
      "nail spa towson",
      "raindrop natural nail spa",
      "bella v nails and spa",
      "destin nail spa of hamilton",
      "elegance nail & spa naperville il",
      "expert nails & spa willoughby",
      "fon s nail and spa",
      "gainey nails & spa",
      "harbor point nail & spa",
      "lc nails and spa jacksonville reviews",
      "nv nail up & spa",
      "salt valley nail spa",
      "angelina nail spa 2",
      "adore nails and lashes",
      "archdale nail spa",
      "brillante nails spa",
      "esthetique nail spa",
      "fab nail & lash spa",
      "forever french nails & organic spa",
      "k1 nails & spa",
      "ln nail spa",
      "nail tip & spa",
      "new look hair & nail spa",
      "oak grove nails spa",
      "polish'd nail boutique",
      "sugar coat nail spa",
      "sugar polish west midtown",
      "valley nails spa",
      "ab nails and spa",
      "chic nail spa brookfield",
      "envy nail spa shadyside",
      "gel nails boardman oh",
      "lashes n nails",
      "mandara nail spa",
      "nails 21 spa framingham",
      "polish nails easton md",
      "west nyack joanna nail spa",
      "mimi nails & spa of bensalem",
      "elegance nail spa naperville",
      "oak grove nail spa",
      "qtee nails & lashes",
      "wilton nail & spa",
      "aqua lifestyle nail salon & spa",
      "crystal beauty nail and spa carthage",
      "divine nail spa leesburg va",
      "enjoy nail and spa",
      "essences nail & day spa",
      "got nails & spa",
      "icolor nails & spa",
      "joseph nail spa",
      "lunar nail spa",
      "lv spa & nails grand junction co",
      "mia nail spa macomb il",
      "nail spa by joyce",
      "nails spa sterling il",
      "neve nails & spa",
      "nu nu nails & spa",
      "pink polish nail spa",
      "posh and polished nail spa",
      "saradet nails and spa inc",
      "shui nails & spa",
      "td's nail & spa reviews",
      "trendy nails spa photos",
      "3d nail spa waterbury ct",
      "cella's nail art studio",
      "house of nails spa ii",
      "jessi's nails & spa",
      "marie nails & spa",
      "naples salon & day spa",
      "artisan nails spa",
      "angelina nail spa",
      "chateau nails spa"
    ],
    "brandedQueries": [
      "lacquer gallery",
      "gloss bar dc",
      "the nailery",
      "blue lotus shelton",
      "gel factory",
      "sparenity",
      "utopia 1",
      "le lani",
      "bellacures sherman oaks",
      "polish room 1",
      "raizun",
      "simply polished",
      "toe paradise arlington heights",
      "utopia kenosha",
      "enails savage",
      "level up lafayette",
      "nailed it pdx",
      "utopia kenosha wi",
      "glossbar dc",
      "nailsaholic",
      "twisted nailz",
      "cat lynn",
      "urbanchic nailbar cary nc",
      "easy beauty space",
      "inails and lash",
      "la belle summerhill",
      "sheer bliss kings highway",
      "nathalys",
      "nailspree",
      "avalon crofton",
      "caliwill",
      "enails savage mn",
      "end results",
      "glossary north point",
      "lush madison",
      "peachbling",
      "posh polished 30a",
      "high cotton athens al",
      "blue sky cherry creek",
      "paradiso hollister ca",
      "pink polish west ashley",
      "tip to toe cheyenne wy",
      "beauty by lid scv",
      "lacquer gallery hair",
      "1010 n glebe rd arlington va",
      "1010 north glebe road arlington va",
      "301 newbury st danvers ma",
      "eden of ashburn",
      "kosmo rockville",
      "nailed it tampa",
      "pnd lynbrook",
      "sugar polish west midtown",
      "6616 s parker rd aurora co",
      "euphoria norwell ma",
      "glitz and glam st augustine",
      "nailery 2",
      "nailtique on main street",
      "sadies manteca",
      "polished rochester",
      "sage & grey",
      "ph7 woodbury",
      "atir cary st",
      "beauty me bellevue",
      "nailed it watertown",
      "nailsplash livingston nj",
      "new beautiful q inc.",
      "new nichole",
      "studio mar",
      "sugar polish midtown",
      "the blow down",
      "we nailed it",
      "polished bluffton",
      "3742 durham chapel hill blvd durham nc 27707",
      "about an inch",
      "anthony vince brookfield wi",
      "claws by vee",
      "menta canela",
      "nashs lashes westport",
      "sugar polish howell",
      "5c blink syosset",
      "adora silverdale",
      "boramey",
      "house of manicare",
      "lush laquer",
      "nailholix dublin ohio",
      "polished zelienople pa",
      "queen polish shelton ct",
      "thenailbox",
      "b lucie",
      "cutiecle",
      "from tip to toe",
      "la vena smithtown",
      "elite nailed it glen ridge",
      "101 gatlin ave orlando fl 32806",
      "aura woburn",
      "bellaluxe ellicott city",
      "jessnails",
      "jonathon khoi maumee ohio",
      "lotus carrollton ga",
      "services offered by color vault",
      "znails south zanesville ohio",
      "you got nailed encino",
      "lacquer gallery columb",
      "spataneo",
      "styles by nikki param",
      "80 e wynnewood rd wynnewood pa 19096"
    ]
  }
} as const;

export type SeoKeywordBucket = keyof typeof seoKeywordCorpus.grouped;

export function getSeoKeywordsForPage(page: 'home' | 'search' | 'deals' | 'listings' | 'business') {
  const { featured, grouped } = seoKeywordCorpus;
  if (page === 'home') return [...featured.slice(0, 48), ...grouped.localIntent.slice(0, 24), ...grouped.serviceIntent.slice(0, 24)];
  if (page === 'search') return [...grouped.localIntent.slice(0, 96), ...grouped.highIntent.slice(0, 64)];
  if (page === 'deals') return [...grouped.dealIntent.slice(0, 72), ...grouped.highIntent.slice(0, 32)];
  if (page === 'listings') return [...grouped.localIntent.slice(0, 120), ...grouped.highIntent.slice(0, 48)];
  return [...grouped.brandedQueries.slice(0, 72), ...grouped.highIntent.slice(0, 24)];
}

// Keep visible on-page keyword clusters readable and useful for people:
// drop address-like, malformed, or ultra-noisy terms.
const DISPLAY_KEYWORD_BLOCKLIST = [/^\d+\b/, /\b\d{5}\b/, /\b(offered|services offered by)\b/i, /\binc\.?\b/i, /\bllc\b/i];

export function getCleanSeoKeywordsForPage(page: 'home' | 'search' | 'deals' | 'listings' | 'business', limit = 18) {
  const seen = new Set<string>();
  const cleaned = getSeoKeywordsForPage(page)
    .map((k) => k.trim())
    .filter((k) => k.length >= 4 && k.length <= 56)
    .filter((k) => !DISPLAY_KEYWORD_BLOCKLIST.some((pattern) => pattern.test(k)))
    .filter((k) => {
      if (seen.has(k)) return false;
      seen.add(k);
      return true;
    });
  return cleaned.slice(0, limit);
}
